import {useEffect,useState} from "react";
import {Modal} from "react-bootstrap";
import {Link,Navigate,useNavigate,useParams,useSearchParams} from "react-router-dom";
import {ArrowLeft,CalendarDays,ChevronRight,FileText,Plus,RefreshCw,Search,SquarePen,Trash2,UserRound} from "lucide-react";
import {publishingWorkflowSections} from "../../data/publishingWorkflowSections.js";
import {workflowFields,workflowStatuses,readable} from "../../data/publishingSchema.js";
import {publishingApi,useCatalog,useBookCatalog,idOf,bookCoverUrl} from "../../utils/publishingApi.js";
import PublishingRecordForm from "./PublishingRecordForm.jsx";
import {FilePreview} from "./FileBrowseField.jsx";
import "../../styles/PublishingWorkspace.css";

const stages=publishingWorkflowSections.flatMap(section=>section.items.map(item=>({key:item.path.replace("/publishing/",""),label:`${section.label} / ${item.label}`})));
const workerName=worker=>{const details=worker?.details&&typeof worker.details==="object"?worker.details:{};return [details.firstName,details.lastName].filter(Boolean).join(" ")||worker?.name||worker?.username||worker?.email||"Unknown worker";};
const shortDate=value=>String(value||"").slice(0,10);

function WorkflowBoard({section,workflow,user}){
 const catalog=useCatalog();
 const booksCatalog=useBookCatalog();
 const navigate=useNavigate();
 const [params]=useSearchParams();
 const recordId=params.get("record");
 const initialStage=workflow?`${section.id}/${workflow}`:section.items[0].path.replace("/publishing/","");
 const currentUserId=idOf(user?._id||user?.id||user);
 const businessId=idOf(user?.currentBusiness||user?.business||user?.businessRef||user?.business_id);
 const initialRecord=()=>{const [module,stage]=initialStage.split("/");return {bookId:"",title:"",author:"",owner:workerName(user),ownerId:currentUserId,module,workflow:stage,status:"not-started",dueDate:"",publisher:"",genres:[],categories:[],notes:"",details:{}};};
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [workers,setWorkers]=useState([]),[workersError,setWorkersError]=useState("");
 const [selectedId,setSelectedId]=useState(recordId||"");
 const [form,setForm]=useState(()=>params.get("new")==="1"?initialRecord():null);
 const [deleting,setDeleting]=useState(null),[deletingBusy,setDeletingBusy]=useState(false);
 const [saving,setSaving]=useState(false),[search,setSearch]=useState(""),[status,setStatus]=useState("");
 const [uploading,setUploading]=useState(0);
 const [message,setMessage]=useState("");

 const reload=async()=>{setLoading(true);setError("");try{const data=await publishingApi("publishing/records");setRows(data.records||[]);}catch(cause){setError(cause.message);}finally{setLoading(false);}};
 useEffect(()=>{let active=true;publishingApi("publishing/records").then(data=>{if(active){setRows(data.records||[]);if(recordId)setSelectedId(recordId);}}).catch(cause=>{if(active)setError(cause.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[recordId]);
 useEffect(()=>{let active=true;publishingApi(`users${businessId?`?business=${encodeURIComponent(businessId)}`:""}`).then(data=>{if(!active)return;const results=Array.isArray(data.data)?data.data:[];const enabled=results.filter(worker=>worker.isActive!==false);const current=enabled.some(worker=>idOf(worker)===currentUserId)?enabled:[...enabled,...(user?[user]:[])];setWorkers(current.sort((a,b)=>workerName(a).localeCompare(workerName(b))));const matched=current.find(worker=>idOf(worker)===currentUserId);if(matched)setForm(previous=>previous&&!previous._id&&previous.ownerId===currentUserId?{...previous,owner:workerName(matched)}:previous);}).catch(cause=>{if(active)setWorkersError(cause.message);});return()=>{active=false;};},[businessId,currentUserId,user]);

 const newRecord=()=>{const record=initialRecord();const current=workers.find(worker=>idOf(worker)===currentUserId);if(current)record.owner=workerName(current);setForm(record);setError("");setMessage("");};
 const save=async event=>{event.preventDefault();if(uploading)return;if(!form.bookId&&!form._id){setError("Choose a book from Book Management before saving.");return;}setSaving(true);setError("");setMessage("");try{const {record}=await publishingApi(`publishing/records${form._id?`/${form._id}`:""}`,{method:form._id?"PUT":"POST",body:form});setForm(null);setSelectedId(record._id);setMessage(`Saved ${record.title}.`);await reload();}catch(cause){setError(cause.message);}finally{setSaving(false);}};
 const remove=async()=>{if(!deleting)return;setDeletingBusy(true);setError("");try{await publishingApi(`publishing/records/${deleting._id}`,{method:"DELETE"});setRows(previous=>previous.filter(row=>row._id!==deleting._id));if(selectedId===deleting._id)setSelectedId("");setMessage(`Deleted ${deleting.title}.`);setDeleting(null);}catch(cause){setError(cause.message);}finally{setDeletingBusy(false);}};
 const visible=rows.filter(row=>row.module===section.id&&(!workflow||row.workflow===workflow)&&(!status||row.status===status)&&`${row.title} ${row.author} ${row.owner}`.toLowerCase().includes(search.toLowerCase()));
 const selected=visible.find(row=>row._id===selectedId)||visible[0]||null;
 const selectedStage=selected?`${selected.module}/${selected.workflow}`:"";
 const selectedBook=booksCatalog.books.find(book=>idOf(book)===idOf(selected?.bookId));
 const selectedCover=bookCoverUrl(selectedBook);
 const selectedPublisher=catalog.publishers.find(row=>idOf(row)===idOf(selected?.publisher));
 const selectedGenres=catalog.genres.filter(item=>(selected?.genres||[]).map(idOf).includes(idOf(item))).map(item=>item.name).join(", ");
 const selectedCategories=catalog.categories.filter(item=>(selected?.categories||[]).map(idOf).includes(idOf(item))).map(item=>item.name).join(", ");
 const selectedDetails=Object.entries(selected?.details?.[selectedStage]||{}).filter(([,value])=>value!==""&&value!==null&&value!==undefined);
 const pageTitle=workflow?section.items.find(item=>item.path.endsWith(`/${workflow}`))?.label:section.label;

 return <section className="publishing-workspace publishing-workflow-page">
  <header className="publishing-workflow-header"><div><Link className="publishing-back-link" to="/publishing/dashboard"><ArrowLeft size={17}/> Publishing dashboard</Link><p className="publishing-form-eyebrow">{section.label}</p><h1>{pageTitle}</h1><p>{section.summary}</p></div><label className="publishing-step-picker">Workflow step<select className="form-select" aria-label="Choose workflow step" value={workflow?section.items.find(item=>item.path.endsWith(`/${workflow}`))?.path:section.path} onChange={event=>navigate(event.target.value)}><option value={section.path}>All {section.label}</option>{section.items.map(item=><option value={item.path} key={item.path}>{item.label}</option>)}</select></label></header>
  {error&&<div className="alert alert-danger" role="alert">{error}</div>}{message&&<div className="alert alert-success" role="status">{message}</div>}
  <div className="publishing-workflow-layout"><main className="publishing-workflow-main">{selected?<article className="publishing-record-detail"><div className="publishing-record-detail-top"><span className="publishing-form-eyebrow">Selected record</span><span className="publishing-record-status">{readable(selected.status)}</span></div><div className="publishing-record-book-heading">{selectedCover&&<img src={selectedCover} alt="Book cover"/>}<div><h2>{selected.title}</h2><p className="publishing-record-author">{selected.author||"Author not set"}</p></div></div><div className="publishing-record-detail-actions"><button type="button" className="btn btn-primary" onClick={()=>setForm({...selected,dueDate:shortDate(selected.dueDate)})}><SquarePen size={16}/> Edit record</button><button type="button" className="btn btn-outline-danger" onClick={()=>setDeleting(selected)}><Trash2 size={16}/> Delete</button></div><div className="publishing-record-facts"><div><span>Workflow</span><strong>{stages.find(stage=>stage.key===selectedStage)?.label||selectedStage}</strong></div><div><span>Assigned owner</span><strong>{selected.owner||"Unassigned"}</strong></div><div><span>Due date</span><strong>{shortDate(selected.dueDate)||"No due date"}</strong></div><div><span>Publisher</span><strong>{selectedPublisher?.name||"Unassigned"}</strong></div><div><span>Genres</span><strong>{selectedGenres||"Not set"}</strong></div><div><span>Categories</span><strong>{selectedCategories||"Not set"}</strong></div></div><section className="publishing-record-detail-section"><h3>Stage details</h3>{selectedDetails.length?<dl>{selectedDetails.map(([key,value])=><div key={key}><dt>{workflowFields[selectedStage]?.find(field=>field.key===key)?.label||key}</dt><dd>{workflowFields[selectedStage]?.find(field=>field.key===key)?.type==="file"?<FilePreview value={value} label={key}/>:value}</dd></div>)}</dl>:<p>No details added for this stage.</p>}</section>{selected.notes&&<section className="publishing-record-detail-section"><h3>Notes</h3><p className="publishing-reference-content">{selected.notes}</p></section>}{!!selected.history?.length&&<details className="publishing-record-detail-section"><summary>Stage and status history</summary><ul className="publishing-history">{selected.history.map((entry,index)=><li key={entry._id||index}>{new Date(entry.at).toLocaleString()} — {readable(entry.stage)} — {readable(entry.status)}</li>)}</ul></details>}</article>:<div className="publishing-workflow-placeholder"><FileText size={32}/><h2>No record selected</h2><p>Choose a record on the right or add a new one.</p><button type="button" className="btn btn-primary" onClick={newRecord}><Plus size={17}/> Add record</button></div>}</main>
   <aside className="publishing-records-panel"><div className="publishing-records-head"><div><p className="publishing-form-eyebrow">Your worklist</p><h2>Records <span>{visible.length}</span></h2></div><button type="button" className="publishing-records-refresh" onClick={reload} disabled={loading||saving} aria-label="Refresh records"><RefreshCw size={18}/></button></div><div className="publishing-records-actions"><button type="button" className="btn btn-primary" disabled={saving} onClick={newRecord}><Plus size={16}/> Add record</button><Link to="/publishers">Publisher directory <ChevronRight size={15}/></Link></div><label className="publishing-records-search"><Search size={18}/><input aria-label="Search workflow records" placeholder="Search records" value={search} onChange={event=>setSearch(event.target.value)}/></label><select aria-label="Filter status" className="form-select publishing-records-filter" value={status} onChange={event=>setStatus(event.target.value)}><option value="">All statuses</option>{workflowStatuses.map(value=><option key={value} value={value}>{readable(value)}</option>)}</select><div className="publishing-records-list">{loading?<p role="status">Loading records…</p>:visible.length?visible.map(row=><button type="button" key={row._id} className={`publishing-record-card${selected?._id===row._id?" is-selected":""}`} disabled={saving} onClick={()=>setSelectedId(row._id)}><span className="publishing-record-card-title">{row.title}</span><span className="publishing-record-card-subtitle">{row.author||"Author not set"}</span><span className="publishing-record-card-meta"><span>{readable(row.workflow)}</span><span>{readable(row.status)}</span></span><span className="publishing-record-card-footer"><span><UserRound size={14}/>{row.owner||"Unassigned"}</span><span><CalendarDays size={14}/>{shortDate(row.dueDate)||"No due date"}</span></span></button>):<p className="publishing-records-empty">No records match this view.</p>}</div></aside></div>
  <PublishingRecordForm form={form} setForm={setForm} section={section} catalog={catalog} books={booksCatalog.books} booksLoading={booksCatalog.loading} booksError={booksCatalog.error} workers={workers} workersError={workersError} currentUserId={currentUserId} saving={saving} uploading={uploading} error={error} onSave={save} onClose={()=>setForm(null)} onUploadChange={delta=>setUploading(previous=>Math.max(0,previous+delta))}/>
  <Modal show={!!deleting} onHide={()=>{if(!deletingBusy)setDeleting(null);}} centered backdrop="static" dialogClassName="publishing-delete-dialog"><Modal.Header closeButton={!deletingBusy}><Modal.Title>Delete publishing record?</Modal.Title></Modal.Header><Modal.Body>{error&&<div className="alert alert-danger" role="alert">{error}</div>}<p><strong>{deleting?.title}</strong> and its stage history will be permanently removed.</p></Modal.Body><Modal.Footer><button type="button" className="btn btn-outline-secondary" disabled={deletingBusy} onClick={()=>setDeleting(null)}>Cancel</button><button type="button" className="btn btn-danger" disabled={deletingBusy} onClick={remove}>{deletingBusy?"Deleting…":"Delete record"}</button></Modal.Footer></Modal>
 </section>;
}

export default function PublishingModulePage({user}){const {module,workflow}=useParams();const section=publishingWorkflowSections.find(item=>item.id===module);if(!section||(workflow&&!workflowFields[`${module}/${workflow}`]))return <Navigate to="/404" replace/>;return <WorkflowBoard key={`${module}/${workflow||""}`} section={section} workflow={workflow} user={user}/>;}
