import {useEffect,useState} from "react";
import {Link,Navigate,useParams} from "react-router-dom";
import {publishingReferencePages} from "../../data/publishingWorkflowSections.js";
import {publishingSources,houseReferenceDrafts} from "../../data/publishingReferenceSources.js";
import {referenceStatuses} from "../../data/publishingSchema.js";
import {publishingApi} from "../../utils/publishingApi.js";
import "../../styles/PublishingWorkspace.css";
function ReferenceEntries({page}){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[form,setForm]=useState(null),[saving,setSaving]=useState(false),[error,setError]=useState(""),[search,setSearch]=useState("");
 const reload=async()=>{setLoading(true);setError("");try{setRows((await publishingApi("publishing/references")).records);}catch(error){setError(error.message);}finally{setLoading(false);}};
 useEffect(()=>{reload();},[]);
 const save=async event=>{event.preventDefault();setSaving(true);setError("");try{await publishingApi(`publishing/references${form._id?`/${form._id}`:""}`,{method:form._id?"PUT":"POST",body:form});setForm(null);await reload();}catch(error){setError(error.message);}finally{setSaving(false);}};
 const visible=rows.filter(row=>row.section===page.slug&&`${row.title} ${row.content}`.toLowerCase().includes(search.toLowerCase()));
 return <section className="publishing-workspace"><Link to="/publishing/dashboard">← Publishing dashboard</Link><h1>{page.title}</h1><p>Save house standards, detailed guidance, source links and approval status for your publishing team.</p><div className="publishing-toolbar"><input className="form-control" aria-label="Search references" placeholder="Search reference content" value={search} onChange={e=>setSearch(e.target.value)}/><button className="btn btn-primary" onClick={()=>setForm({section:page.slug,title:"",content:"",sourceUrl:"",status:"draft"})}>Add reference</button><button className="btn btn-outline-secondary" onClick={reload}>Refresh</button></div>{error&&<div className="alert alert-danger" role="alert">{error}</div>}
 <aside className="publishing-reference"><h2>Source library</h2>{publishingSources[page.slug].map(source=><p key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title}</a><br/>{source.note}</p>)}<button className="btn btn-outline-primary" disabled={saving} onClick={()=>setForm({section:page.slug,title:page.title+" — house guidance",content:houseReferenceDrafts[page.slug],sourceUrl:publishingSources[page.slug][0].url,status:"draft"})}>Review and save house guidance</button></aside>
 {form&&<form className="publishing-form" onSubmit={save}><h2>{form._id?"Edit reference":"New reference"}</h2><label>Title<input className="form-control" required maxLength={300} value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Guidance / checklist<textarea className="form-control" required rows={12} value={form.content} onChange={e=>setForm({...form,content:e.target.value})}/></label><label>Source URL<input className="form-control" type="url" value={form.sourceUrl} onChange={e=>setForm({...form,sourceUrl:e.target.value})}/></label><label>Status<select className="form-select" value={form.status} onChange={e=>setForm({...form,status:e.target.value})}>{referenceStatuses.map(status=><option key={status}>{status}</option>)}</select></label><div className="publishing-form-actions"><button className="btn btn-primary" disabled={saving}>{saving?"Saving…":"Save reference"}</button><button type="button" className="btn btn-outline-secondary" disabled={saving} onClick={()=>setForm(null)}>Cancel</button></div></form>}
 {loading?<p role="status">Loading references…</p>:visible.map(row=><article className="publishing-reference" key={row._id}><h2>{row.title}</h2><p>{row.status} · Updated {new Date(row.updatedAt).toLocaleDateString()}</p><div className="publishing-reference-content">{row.content}</div>{/^https?:\/\//i.test(row.sourceUrl)&&<p><a href={row.sourceUrl} target="_blank" rel="noreferrer">Source document</a></p>}<button className="btn btn-outline-primary" disabled={saving} onClick={()=>setForm(row)}>Edit reference</button></article>)}{!loading&&!visible.length&&!error&&<p>No saved references in this section. Add your first guideline or checklist.</p>}</section>;
}
export default function PublishingReferencePage(){const {slug}=useParams();const page=publishingReferencePages.find(item=>item.slug===slug);return page?<ReferenceEntries key={slug} page={page}/>:<Navigate to="/404" replace/>;}
