import mongoose from "mongoose";
import Order from "../../models/orders/orderModel.js";
import Client from "../../models/clients/clientsModel.js";
import Event from "../../models/events/eventModel.js";

const populate=[{path:"client",model:Client,select:"name firstName lastName company email"},{path:"event",model:Event,select:"eventName eventDate eventTime location status"}];
const decimal=value=>mongoose.Types.Decimal128.fromString(String(value===""||value==null?0:value));
const format=doc=>{const item=doc?.toObject?doc.toObject():doc;return {...item,subtotal:item.subtotal?.toString?.()||"0",tax:item.tax?.toString?.()||"0",discount:item.discount?.toString?.()||"0",total:item.total?.toString?.()||"0"};};
const payloadFrom=body=>({client:body.client,event:body.event,orderNumber:String(body.orderNumber||"").trim().toUpperCase(),status:body.status||"draft",serviceType:body.serviceType||"delivery",subtotal:decimal(body.subtotal),tax:decimal(body.tax),discount:decimal(body.discount),total:decimal(body.total),notes:String(body.notes||"").trim()});
const validate=async body=>{if(!mongoose.Types.ObjectId.isValid(body.client))return "A valid client is required";if(!mongoose.Types.ObjectId.isValid(body.event))return "A valid event is required";if(!String(body.orderNumber||"").trim())return "Order number is required";const values=[body.subtotal,body.tax,body.discount,body.total].map(value=>Number(value||0));if(values.some(value=>!Number.isFinite(value)||value<0))return "Order amounts must be zero or greater";const [client,event]=await Promise.all([Client.exists({_id:body.client}),Event.exists({_id:body.event})]);if(!client)return "Client not found";if(!event)return "Event not found";return "";};

export const createOrder=async(req,res)=>{try{const problem=await validate(req.body);if(problem)return res.status(400).json({success:false,message:problem});const saved=await Order.create(payloadFrom(req.body));const order=await Order.findById(saved._id).populate(populate);return res.status(201).json({success:true,message:"Order created successfully",order:format(order)});}catch(error){if(error.code===11000)return res.status(409).json({success:false,message:"Order number already exists"});return res.status(500).json({success:false,message:"Failed to create order",error:error.message});}};
export const getOrders=async(req,res)=>{try{const orders=await Order.find().populate(populate).sort({createdAt:-1});return res.json({success:true,count:orders.length,orders:orders.map(format)});}catch(error){return res.status(500).json({success:false,message:"Failed to fetch orders",error:error.message});}};
export const getOrderById=async(req,res)=>{try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid order id"});const order=await Order.findById(req.params.id).populate(populate);if(!order)return res.status(404).json({success:false,message:"Order not found"});return res.json({success:true,order:format(order)});}catch(error){return res.status(500).json({success:false,message:"Failed to fetch order",error:error.message});}};
export const updateOrder=async(req,res)=>{try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid order id"});const problem=await validate(req.body);if(problem)return res.status(400).json({success:false,message:problem});const order=await Order.findByIdAndUpdate(req.params.id,payloadFrom(req.body),{returnDocument:"after",runValidators:true}).populate(populate);if(!order)return res.status(404).json({success:false,message:"Order not found"});return res.json({success:true,message:"Order updated successfully",order:format(order)});}catch(error){if(error.code===11000)return res.status(409).json({success:false,message:"Order number already exists"});return res.status(500).json({success:false,message:"Failed to update order",error:error.message});}};
export const deleteOrder=async(req,res)=>{try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid order id"});const order=await Order.findByIdAndDelete(req.params.id);if(!order)return res.status(404).json({success:false,message:"Order not found"});return res.json({success:true,message:"Order deleted successfully"});}catch(error){return res.status(500).json({success:false,message:"Failed to delete order",error:error.message});}};
