// backend/controllers/priority/priorityController.js
import Priority from "../../models/priority/priorityModel.js";
import createCrudController from "../utils/createCrudController.js";

const priorityController=createCrudController({
 Model:Priority,
 dataKey:"priorities",
 defaultSort:{dueDate:1,priorityLevel:-1},
 populate:[
  {path:"lifeArea"},
  {path:"category"},
  {path:"tags"},

  {
   path:"linkedGoal",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"tags"}
   ]
  },
  {
   path:"linkedTask",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"linkedGoal"},
    {path:"linkedHabit"},
    {path:"tags"}
   ]
  },
  {
   path:"linkedHabit",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"tags"}
   ]
  },
  {
   path:"linkedRoutine",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"linkedGoal"},
    {path:"tags"}
   ]
  },
  {
   path:"linkedReminder",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"linkedTask"},
    {path:"linkedGoal"},
    {path:"linkedHabit"},
    {path:"linkedRoutine"},
    {path:"linkedJournalEntry"},
    {path:"linkedMindfulnessEntry"},
    {path:"linkedCalendarEvent"},
    {path:"linkedReview"},
    {path:"tags"}
   ]
  },
  {
   path:"linkedEvent",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"linkedTask"},
    {path:"linkedGoal"},
    {path:"linkedJournalEntry"},
    {path:"tags"}
   ]
  },
  {
   path:"linkedMilestone",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"linkedGoal"},
    {path:"tags"}
   ]
  },
  {
   path:"linkedJournal",
   populate:[
    {path:"lifeArea"},
    {path:"category"},
    {path:"linkedGoals"},
    {path:"linkedHabits"},
    {path:"linkedTasks"},
    {path:"tags"}
   ]
  }
 ]
});

export default priorityController;