import {useMemo,useState} from "react";
import {Button,Col,Form,Row,Table} from "react-bootstrap";

const id=value=>typeof value==="string"?value:String(value?._id||"");
const lines=value=>String(value||"").split(/\r?\n/).map(item=>item.trim()).filter(Boolean);
const blankItem={ingredient:"",metricQuantity:"",metricUnit:"",imperialQuantity:"",imperialUnit:"",cost:"0",notes:""};
const blank={name:"",slug:"",product:"",batchSize:"",batchYield:"",metricUnit:"",imperialUnit:"",items:[],laborCost:"0",packagingCost:"0",overheadCost:"0",targetMarginPercent:"",notes:"",status:""};

export default function CostingForm({initialData={},lookups,onSubmit,saving}){
 const [data,setData]=useState(()=>({...blank,...initialData,product:id(initialData.product),metricUnit:id(initialData.metricUnit),imperialUnit:id(initialData.imperialUnit),status:id(initialData.status),notes:Array.isArray(initialData.notes)?initialData.notes.join("\n"):"",items:(initialData.items||[]).map(row=>({...blankItem,...row,ingredient:id(row.ingredient),metricUnit:id(row.metricUnit),imperialUnit:id(row.imperialUnit),notes:Array.isArray(row.notes)?row.notes.join("\n"):""}))}));
 const set=(name,value)=>setData(previous=>({...previous,[name]:value}));
 const setItem=(index,name,value)=>setData(previous=>({...previous,items:previous.items.map((row,rowIndex)=>rowIndex===index?{...row,[name]:value}:row)}));
 const totals=useMemo(()=>{const material=data.items.reduce((sum,row)=>sum+Number(row.cost||0),0);const total=material+Number(data.laborCost||0)+Number(data.packagingCost||0)+Number(data.overheadCost||0);const unit=Number(data.batchYield)>0?total/Number(data.batchYield):0;const margin=Number(data.targetMarginPercent);return {material,total,unit,price:data.targetMarginPercent!==""&&margin<100?unit/(1-margin/100):0};},[data]);
 const unitOptions=items=>items.map(item=><option key={item._id} value={item._id}>{item.name}{item.symbol?` (${item.symbol})`:""}</option>);
 return <Form onSubmit={event=>{event.preventDefault();onSubmit({...data,notes:lines(data.notes),items:data.items.map(row=>({...row,notes:lines(row.notes)}))});}}><Row className="g-3">
  <Col md={6}><Form.Group><Form.Label>Name</Form.Label><Form.Control required value={data.name} onChange={e=>set("name",e.target.value)}/></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Slug</Form.Label><Form.Control value={data.slug} onChange={e=>set("slug",e.target.value)} placeholder="Generated from name when blank"/></Form.Group></Col>
  <Col md={6}><Form.Group><Form.Label>Product</Form.Label><Form.Select value={data.product} onChange={e=>set("product",e.target.value)}><option value="">No linked product</option>{lookups.products.map(row=><option key={row._id} value={row._id}>{row.name}</option>)}</Form.Select></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Status</Form.Label><Form.Select required value={data.status} onChange={e=>set("status",e.target.value)}><option value="">Select status</option>{lookups.statuses.map(row=><option key={row._id} value={row._id}>{row.name}</option>)}</Form.Select></Form.Group></Col>
  <Col md={3}><Form.Group><Form.Label>Batch size</Form.Label><Form.Control type="number" min="0" step="any" value={data.batchSize} onChange={e=>set("batchSize",e.target.value)}/></Form.Group></Col><Col md={3}><Form.Group><Form.Label>Batch yield</Form.Label><Form.Control type="number" min="0" step="any" value={data.batchYield} onChange={e=>set("batchYield",e.target.value)}/></Form.Group></Col><Col md={3}><Form.Group><Form.Label>Metric unit</Form.Label><Form.Select value={data.metricUnit} onChange={e=>set("metricUnit",e.target.value)}><option value="">None</option>{unitOptions(lookups.metricUnits)}</Form.Select></Form.Group></Col><Col md={3}><Form.Group><Form.Label>Imperial unit</Form.Label><Form.Select value={data.imperialUnit} onChange={e=>set("imperialUnit",e.target.value)}><option value="">None</option>{unitOptions(lookups.imperialUnits)}</Form.Select></Form.Group></Col>
 </Row><div className="d-flex justify-content-between align-items-center mt-4 mb-2"><h2 className="h5 mb-0">Ingredients</h2><Button size="sm" variant="outline-primary" onClick={()=>set("items",[...data.items,{...blankItem}])}>Add line</Button></div><Table responsive bordered size="sm"><thead><tr><th>Ingredient</th><th>Metric qty / unit</th><th>Imperial qty / unit</th><th>Cost</th><th>Notes</th><th></th></tr></thead><tbody>{data.items.length===0&&<tr><td colSpan="6" className="text-muted">No ingredient lines.</td></tr>}{data.items.map((row,index)=><tr key={row._id||index}><td><Form.Select required value={row.ingredient} onChange={e=>setItem(index,"ingredient",e.target.value)}><option value="">Select</option>{lookups.ingredients.map(item=><option key={item._id} value={item._id}>{item.name}</option>)}</Form.Select></td><td><div className="d-flex gap-1"><Form.Control type="number" min="0" step="any" value={row.metricQuantity} onChange={e=>setItem(index,"metricQuantity",e.target.value)}/><Form.Select value={row.metricUnit} onChange={e=>setItem(index,"metricUnit",e.target.value)}><option value="">Unit</option>{unitOptions(lookups.metricUnits)}</Form.Select></div></td><td><div className="d-flex gap-1"><Form.Control type="number" min="0" step="any" value={row.imperialQuantity} onChange={e=>setItem(index,"imperialQuantity",e.target.value)}/><Form.Select value={row.imperialUnit} onChange={e=>setItem(index,"imperialUnit",e.target.value)}><option value="">Unit</option>{unitOptions(lookups.imperialUnits)}</Form.Select></div></td><td><Form.Control type="number" min="0" step="0.01" value={row.cost} onChange={e=>setItem(index,"cost",e.target.value)}/></td><td><Form.Control value={row.notes} onChange={e=>setItem(index,"notes",e.target.value)}/></td><td><Button size="sm" variant="outline-danger" onClick={()=>set("items",data.items.filter((_,rowIndex)=>rowIndex!==index))}>Remove</Button></td></tr>)}</tbody></Table>
 <Row className="g-3"><Col md={3}><Form.Group><Form.Label>Labor cost</Form.Label><Form.Control type="number" min="0" step="0.01" value={data.laborCost} onChange={e=>set("laborCost",e.target.value)}/></Form.Group></Col><Col md={3}><Form.Group><Form.Label>Packaging cost</Form.Label><Form.Control type="number" min="0" step="0.01" value={data.packagingCost} onChange={e=>set("packagingCost",e.target.value)}/></Form.Group></Col><Col md={3}><Form.Group><Form.Label>Overhead cost</Form.Label><Form.Control type="number" min="0" step="0.01" value={data.overheadCost} onChange={e=>set("overheadCost",e.target.value)}/></Form.Group></Col><Col md={3}><Form.Group><Form.Label>Target margin %</Form.Label><Form.Control type="number" min="0" max="99.99" step="any" value={data.targetMarginPercent} onChange={e=>set("targetMarginPercent",e.target.value)}/></Form.Group></Col><Col md={12}><Form.Group><Form.Label>Notes (one per line)</Form.Label><Form.Control as="textarea" rows={2} value={data.notes} onChange={e=>set("notes",e.target.value)}/></Form.Group></Col></Row>
 <div className="mt-3 p-3 bg-light rounded">Material: ${totals.material.toFixed(2)} · Total: ${totals.total.toFixed(2)} · Unit: ${totals.unit.toFixed(2)} · Suggested price: ${totals.price.toFixed(2)}</div><div className="d-flex justify-content-end mt-4"><Button type="submit" disabled={saving}>{saving?"Saving...":"Save Costing"}</Button></div></Form>;
}
