import BlogPost from "../models/blogPostModel.js";

const slugify=value=>String(value||"").trim().toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const normalizeTags=value=>(Array.isArray(value)?value:String(value||"").split(",")).map(tag=>tag.trim().toLowerCase()).filter(Boolean);
const canManage=(user,post)=>user?.role==="admin"||String(post.author)===String(user?._id);

export const getPosts=async(req,res,next)=>{try{const filter={};if(req.query.mine==="true"){if(!req.user)return res.status(401).json({message:"Sign in to view your posts."});filter.author=req.user._id;}else if(req.query.status&&req.user)filter.status=req.query.status;else filter.status="published";if(req.query.category)filter.category=req.query.category;if(req.query.search)filter.$text={$search:req.query.search};const posts=await BlogPost.find(filter).populate("category","name slug").populate("author","username email role").sort({publishedAt:-1,createdAt:-1});res.json(posts);}catch(error){next(error);}};
export const getPost=async(req,res,next)=>{try{const key=req.params.key;const post=await BlogPost.findOne(key.match(/^[a-f\d]{24}$/i)?{$or:[{_id:key},{slug:key}]}:{slug:key}).populate("category","name slug").populate("author","username email role");if(!post)return res.status(404).json({message:"Post not found."});if(post.status!=="published"&&!canManage(req.user,post))return res.status(404).json({message:"Post not found."});res.json(post);}catch(error){next(error);}};
export const createPost=async(req,res,next)=>{try{const title=String(req.body.title||"").trim();if(!title||!req.body.content)return res.status(400).json({message:"Title and content are required."});const status=req.body.status||"draft";const post=await BlogPost.create({...req.body,title,slug:slugify(req.body.slug||title),tags:normalizeTags(req.body.tags),status,author:req.user._id,publishedAt:status==="published"?(req.body.publishedAt||new Date()):null});res.status(201).json(await post.populate(["category",{path:"author",select:"username email role"}]));}catch(error){next(error);}};
export const updatePost=async(req,res,next)=>{try{const post=await BlogPost.findById(req.params.id);if(!post)return res.status(404).json({message:"Post not found."});if(!canManage(req.user,post))return res.status(403).json({message:"You cannot edit this post."});for(const field of ["title","excerpt","content","featuredImage","imageAlt","category","status","publishedAt"])if(req.body[field]!==undefined)post[field]=req.body[field]||null;if(req.body.slug||req.body.title)post.slug=slugify(req.body.slug||req.body.title);if(req.body.tags!==undefined)post.tags=normalizeTags(req.body.tags);if(post.status==="published"&&!post.publishedAt)post.publishedAt=new Date();res.json(await post.save());}catch(error){next(error);}};
export const deletePost=async(req,res,next)=>{try{const post=await BlogPost.findById(req.params.id);if(!post)return res.status(404).json({message:"Post not found."});if(!canManage(req.user,post))return res.status(403).json({message:"You cannot delete this post."});await post.deleteOne();res.json({message:"Post deleted."});}catch(error){next(error);}};
