import Alert from "../../../../components/AppAlert.jsx";
import {Button,Card,Col,Form,Row} from "react-bootstrap";

export default function RecipeGeneralModule({data,lookups,initialData,change,uploadImage,uploadingImage,imageInputKey,imageVersion,imageUrl,setData,setImageInputKey,setImageVersion,newLookups,setNewLookups,createLookup,addLookup,toggleLookup,creatingLookup,reservingNumber,SelectOptions,id}){
 initialData={...initialData,sourceCuisine:data.sourceCuisine||initialData.sourceCuisine,sourceCourse:data.sourceCourse||initialData.sourceCourse,sourceCategory:data.sourceCategory||initialData.sourceCategory,sourceMealType:data.sourceMealType||initialData.sourceMealType};
 return <Card className="recipe-general-module"><Card.Body><Row className="g-3">
  <Col md={6}><div className="recipe-general-field"><Form.Label htmlFor="recipe-name">Recipe Name:</Form.Label><div className="recipe-general-control"><Form.Control id="recipe-name" name="name" value={data.name} onChange={change}/></div></div></Col>
  <Col md={6}><div className="recipe-general-field"><span className="recipe-general-label">Recipe Number:</span><div className="recipe-general-control"><output className={`recipe-number-display${data.recipeNumber?" has-value":""}`}>{reservingNumber?"Generating...":data.recipeNumber||"Generated after primary cuisine, course, and category are selected"}</output><small className="recipe-number-help">Format: CUISINE-COURSE-CATEGORY-####</small></div></div></Col>
  <Col xs={12}><div className="recipe-general-field"><Form.Label htmlFor="recipe-database">Recipe Database:</Form.Label><div className="recipe-general-control"><Form.Control id="recipe-database" value={(lookups.businesses||[]).find(item=>id(item)===data.business)?.legalName||"Recipe Management"} readOnly/><Form.Text>Master recipes belong to this app and can later be linked to a cafe or restaurant.</Form.Text></div></div></Col>
  <Col xs={12}><Card className="recipe-image-upload-card"><Card.Body><Row className="g-3 align-items-center"><Col md={7}><Form.Group><Form.Label>Plated Recipe Image</Form.Label><Form.Control key={imageInputKey} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={uploadImage} disabled={uploadingImage}/><Form.Text>{uploadingImage?"Uploading image with Multer...":data.image?"Choose another image to replace the current photo.":"Choose a photo of the finished plated recipe."}</Form.Text></Form.Group>{data.image?<div className="recipe-image-path"><strong>Stored image:</strong> {data.image}</div>:null}</Col><Col md={5}>{data.image?<div className="recipe-form-image-preview"><img src={imageUrl(data.image,imageVersion)} alt={`${data.name||"Recipe"} plated thumbnail`}/><Button type="button" size="sm" variant="outline-danger" onClick={()=>{setData(prev=>({...prev,image:""}));setImageInputKey(key=>key+1);setImageVersion(Date.now());}}>Clear Image</Button></div>:<div className="recipe-image-empty">No plated image uploaded</div>}</Col></Row></Card.Body></Card></Col>
  {[["Cuisines","cuisines","cuisines","primaryCuisine",initialData.sourceCuisine],["Courses","courses","courses","primaryCourse",initialData.sourceCourse],["Categories","categories","categories","primaryCategory",initialData.sourceCategory]].map(([labelText,field,type,primaryField,detected])=><Col md={4} key={field}><Card className="h-100"><Card.Body><h3 className="h6">{labelText}</h3>{detected&&!data[field].length?<Alert variant="warning" className="py-1 px-2">Detected: <strong>{detected}</strong> <Button type="button" size="sm" variant="link" onClick={()=>createLookup(type,detected,value=>setData(prev=>({...prev,[field]:[...new Set([...prev[field],value])],[primaryField]:prev[primaryField]||value})))}>Create and select</Button></Alert>:null}<div className="mb-2">{(lookups[field]||[]).map(item=><Form.Check key={item._id} type="checkbox" label={item.name} checked={data[field].includes(item._id)} onChange={()=>toggleLookup(field,item._id)}/>)}</div><div className="d-flex gap-2"><Form.Control size="sm" value={newLookups[field]} onChange={e=>setNewLookups(prev=>({...prev,[field]:e.target.value}))} placeholder={`New ${labelText.slice(0,-1).toLowerCase()}`}/><Button type="button" size="sm" onClick={()=>addLookup(type,field,field)} disabled={!newLookups[field].trim()||Boolean(creatingLookup)}>Add</Button></div></Card.Body></Card></Col>)}
  <Col md={4}><Form.Group><Form.Label>Primary Cuisine for Number</Form.Label><Form.Select name="primaryCuisine" value={data.primaryCuisine} onChange={change}><SelectOptions items={(lookups.cuisines||[]).filter(item=>data.cuisines.includes(item._id))} placeholder="Select primary cuisine"/></Form.Select></Form.Group></Col><Col md={4}><Form.Group><Form.Label>Primary Course for Number</Form.Label><Form.Select name="primaryCourse" value={data.primaryCourse} onChange={change}><SelectOptions items={(lookups.courses||[]).filter(item=>data.courses.includes(item._id))} placeholder="Select primary course"/></Form.Select></Form.Group></Col><Col md={4}><Form.Group><Form.Label>Primary Category for Number</Form.Label><Form.Select name="primaryCategory" value={data.primaryCategory} onChange={change}><SelectOptions items={(lookups.categories||[]).filter(item=>data.categories.includes(item._id))} placeholder="Select primary category"/></Form.Select></Form.Group></Col>
  <Col md={6}><Form.Group><Form.Label>Meal Period (Optional)</Form.Label>{initialData.sourceMealType&&!data.mealType?<Alert variant="warning" className="py-1 px-2 mb-2">Detected: <strong>{initialData.sourceMealType}</strong><Button type="button" size="sm" variant="link" onClick={()=>createLookup("meal-types",initialData.sourceMealType,value=>setData(prev=>({...prev,mealType:value})))}>Create and select</Button></Alert>:null}<Form.Select name="mealType" value={data.mealType} onChange={change}><SelectOptions items={lookups.mealTypes} placeholder="Not assigned"/></Form.Select></Form.Group></Col>
  <Col md={6}><div className="recipe-add-meal-period"><span className="recipe-add-meal-period-label">Add Meal Period:</span><Form.Control value={newLookups.mealTypes} onChange={e=>setNewLookups(prev=>({...prev,mealTypes:e.target.value}))}/><Button type="button" onClick={()=>addLookup("meal-types","mealType","mealTypes")} disabled={!newLookups.mealTypes.trim()||Boolean(creatingLookup)}>Add and Select</Button></div></Col>
  <Col md={8}><Form.Group><Form.Label>General Description</Form.Label><Form.Control as="textarea" rows={3} name="generalDescription" value={data.generalDescription} onChange={change}/></Form.Group></Col><Col md={4}><Form.Group><Form.Label>Suggested Price</Form.Label><Form.Control type="number" min="0" step="0.01" name="suggestedPrice" value={data.suggestedPrice} onChange={change}/></Form.Group></Col><Col xs={12}><Form.Group><Form.Label>Menu Description</Form.Label><Form.Control as="textarea" rows={2} name="menuDescription" value={data.menuDescription} onChange={change}/></Form.Group></Col><Col md={4}><Form.Group><Form.Label>Origin</Form.Label><Form.Control name="origin" value={data.origin} onChange={change}/></Form.Group></Col><Col md={4}><Form.Group><Form.Label>History</Form.Label><Form.Control as="textarea" rows={2} name="history" value={data.history} onChange={change}/></Form.Group></Col><Col md={4}><Form.Group><Form.Label>Cultural Significance</Form.Label><Form.Control as="textarea" rows={2} name="culturalSignificance" value={data.culturalSignificance} onChange={change}/></Form.Group></Col><Col xs={12}><Form.Check type="switch" name="isActive" label="Active recipe" checked={data.isActive} onChange={change}/></Col>
 </Row></Card.Body></Card>;
}
