import {useEffect,useState} from "react";
import {Container,Row,Col,Card,Button,Form,Modal,Alert,ProgressBar,Badge} from "react-bootstrap";
import {formatDate,unwrapList} from "../../utils/projectApi.js";

export default function ProjectsPage(){
 const [projects,setProjects]=useState([]),[error,setError]=useState(""),[show,setShow]=useState(false);
 const [form,setForm]=useState({name:"",description:"",status:"planning",priority:"normal",dueDate:""});
 const load=async()=>{const response=await fetch("/api/projects");if(!response.ok)throw new Error("Unable to load projects");setProjects(unwrapList(await response.json()));};
 useEffect(()=>{queueMicrotask(()=>load().catch(err=>setError(err.message)));},[]);
 const save=async event=>{event.preventDefault();const response=await fetch("/api/projects",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!response.ok)return setError("Unable to create project");setShow(false);setForm({name:"",description:"",status:"planning",priority:"normal",dueDate:""});await load();};
 return <Container fluid="lg" className="py-4"><div className="d-flex justify-content-between align-items-start mb-4"><div><h1>Projects</h1><p className="text-muted">Create and manage individual projects.</p></div><Button onClick={()=>setShow(true)}>New Project</Button></div>{error&&<Alert variant="danger">{error}</Alert>}<Row className="g-3">{projects.map(project=><Col md={6} xl={4} key={project._id}><Card className="h-100"><Card.Body><div className="d-flex justify-content-between"><Card.Title>{project.name}</Card.Title><Badge>{project.status}</Badge></div><Card.Text>{project.description||"No description"}</Card.Text><ProgressBar now={project.progress||0} label={`${project.progress||0}%`}/><small className="d-block text-muted mt-3">Due {formatDate(project.dueDate)}</small></Card.Body></Card></Col>)}</Row><Modal show={show} onHide={()=>setShow(false)} centered><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>New Project</Modal.Title></Modal.Header><Modal.Body><Form.Group className="mb-3"><Form.Label>Name</Form.Label><Form.Control required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Form.Group><Form.Group className="mb-3"><Form.Label>Description</Form.Label><Form.Control as="textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Form.Group><Row><Col><Form.Label>Status</Form.Label><Form.Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="planning">Planning</option><option value="active">Active</option><option value="on-hold">On Hold</option></Form.Select></Col><Col><Form.Label>Due Date</Form.Label><Form.Control type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></Col></Row></Modal.Body><Modal.Footer><Button variant="outline-secondary" onClick={()=>setShow(false)}>Cancel</Button><Button type="submit">Save Project</Button></Modal.Footer></Form></Modal></Container>;
}
