import {Navbar,Nav,NavDropdown,Container} from "react-bootstrap";
import {useLocation,NavLink,Link} from "react-router-dom";
import {useIcons} from "@shared";
import "./Navigation.css";

const ADMIN_USER_IDS=["69af088d21b4580a8cb6614b"];
const OWNER_ROLE_IDS=["69edf92e1e6593dd5369f718"];
const ADMIN_ROLE_IDS=["69edf92e1e6593dd5369f719","69d389f609a4ebea1c3f634e","69d46bce86ec944e3cab4566"];
const MANAGER_ROLE_IDS=["69edf92e1e6593dd5369f71a","69d389f609a4ebea1c3f634f"];
const getId=value=>String(typeof value==="string"?value:value?._id?.$oid||value?._id||value?.id?.$oid||value?.id||"").toLowerCase().trim();

export default function Navigation({user,onLogout}){const location=useLocation();const {FontAwesomeIcons}=useIcons();const roles=[user?.role,user?.roleId,user?.currentRole,user?.activeRole,...(user?.roleAssignments||[]).map(item=>item.role)].filter(Boolean);const roleIds=roles.map(getId);const roleNames=roles.map(role=>String(typeof role==="object"?role.name||role.title||"":role||"").toLowerCase());const owner=ADMIN_USER_IDS.includes(getId(user))||roleIds.some(id=>OWNER_ROLE_IDS.includes(id))||roleNames.includes("owner");const admin=owner||roleIds.some(id=>ADMIN_ROLE_IDS.includes(id))||roleNames.some(name=>["admin","administrator"].includes(name));const manager=admin||roleIds.some(id=>MANAGER_ROLE_IDS.includes(id))||roleNames.includes("manager");const canAdmin=admin||manager;const active=path=>location.pathname.startsWith(path);
 return <Navbar expand="lg" className="app-nav"><Container><Navbar.Brand as={Link} to="/" className="app-nav-brand"><span className="me-2">{FontAwesomeIcons.Home}</span>Home</Navbar.Brand><Navbar.Toggle aria-controls="main-nav" className="app-nav-toggle"/><Navbar.Collapse id="main-nav"><Nav className="me-auto app-nav-links">
  {user&&<Nav.Link as={NavLink} to="/dashboard"><span className="me-2">{FontAwesomeIcons.Feedback}</span>Dashboard</Nav.Link>}
  <Nav.Link as={NavLink} to="/blog"><span className="me-2">{FontAwesomeIcons.Book}</span>Blog</Nav.Link>
  <NavDropdown title={<><span className="me-2">{FontAwesomeIcons.Book}</span>Articles</>} id="articles-dropdown" active={active("/admin/posts")}><NavDropdown.Item as={NavLink} to="/blog">Published Articles</NavDropdown.Item>{user&&<><NavDropdown.Item as={NavLink} to="/admin/posts">Manage Posts</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/admin/posts/new">Create Article</NavDropdown.Item></>}</NavDropdown>
  <NavDropdown title={<><span className="me-2">{FontAwesomeIcons.List}</span>Reference</>} id="reference-dropdown" active={active("/reference")}><NavDropdown.Item as={NavLink} to="/reference">Categories & Publishing</NavDropdown.Item></NavDropdown>
  <Nav.Link as={NavLink} to="/about"><span className="me-2">{FontAwesomeIcons.About}</span>About</Nav.Link><Nav.Link as={NavLink} to="/contact"><span className="me-2">{FontAwesomeIcons.Contact}</span>Contact</Nav.Link>
 </Nav>{canAdmin&&<Nav><NavDropdown title={<><span className="me-2">{FontAwesomeIcons.Admin}</span>Admin</>} id="admin-dropdown" active={active("/admin")||active("/users")||active("/permissions")}><NavDropdown.Item as={NavLink} to="/admin">Admin Dashboard</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/admin/posts">Blog Posts</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/reference">Blog Categories</NavDropdown.Item><NavDropdown.Divider/><NavDropdown.Item as={NavLink} to="/admin/businesses">Businesses</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/admin/business-types">Business Types</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/admin/app-keys">App Keys</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/admin/footers">Footers</NavDropdown.Item><NavDropdown.Divider/><NavDropdown.Item as={NavLink} to="/users">Users</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/permissions">Permissions</NavDropdown.Item><NavDropdown.Item as={NavLink} to="/admin/business-roles-permissions">Roles & Permissions</NavDropdown.Item></NavDropdown></Nav>}
 <Nav>{user?<NavDropdown title={<><span className="me-2">{FontAwesomeIcons.Account}</span>{user.username||user.name||user.email||"Account"}</>}><NavDropdown.Item as={NavLink} to="/profile"><span className="me-2">{FontAwesomeIcons.Profile}</span>Profile</NavDropdown.Item><NavDropdown.Item onClick={onLogout}><span className="me-2">{FontAwesomeIcons.Logout}</span>Logout</NavDropdown.Item></NavDropdown>:<Nav.Link as={NavLink} to="/login"><span className="me-2">{FontAwesomeIcons.Login}</span>Login</Nav.Link>}</Nav></Navbar.Collapse></Container></Navbar>;
}
