import {useCallback,useEffect,useMemo,useState} from "react";
import {Alert,Button,Form,Modal,Spinner} from "react-bootstrap";
import {Anchor,ExternalLink,Plus,Radio,Search,ShieldAlert} from "lucide-react";
import {getObjectId,loadCurrentBusiness} from "../../utils/currentBusiness.js";
import "../../styles/OperationalCodesReference.css";

const emptyForm={service:"police",code:"",title:"",meaning:"",category:"",jurisdiction:"",sourceName:"",sourceUrl:"",notes:"",isActive:true};
const token=()=>localStorage.getItem("token")||sessionStorage.getItem("token")||"";
const headers=extra=>({Authorization:`Bearer ${token()}`,...extra});
const roleName=value=>String(typeof value==="object"?value?.name||value?.title||value?.code||"":value||"").toLowerCase();

export default function OperationalCodesReferencePage({user,service,moduleName,endpoint,title,subtitle,defaultJurisdiction=""}){
 const [businessId,setBusinessId]=useState("");const [records,setRecords]=useState([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [notice,setNotice]=useState(null);const [error,setError]=useState("");const [showForm,setShowForm]=useState(false);const [editing,setEditing]=useState(null);const [form,setForm]=useState({...emptyForm,service});const [permission,setPermission]=useState({create:false,update:false,delete:false,admin:false});
 const roles=[user?.role,user?.currentRole,...(user?.roleAssignments||[]).map(item=>item.role)].map(roleName);
 const privileged=roles.some(role=>["owner","business owner","app owner","super admin","admin","administrator"].includes(role));
 const canCreate=privileged||permission.create||permission.admin;const canUpdate=privileged||permission.update||permission.admin;const canDelete=privileged||permission.delete||permission.admin;

 const load=useCallback(async()=>{setLoading(true);setError("");try{const business=await loadCurrentBusiness();const nextBusinessId=getObjectId(business);setBusinessId(nextBusinessId);const codeResponse=await fetch(`${endpoint}?business=${encodeURIComponent(nextBusinessId)}`,{headers:headers()});const codeData=await codeResponse.json().catch(()=>({}));if(!codeResponse.ok)throw new Error(codeData.message||`Failed to load ${title}.`);setRecords(Array.isArray(codeData.data)?codeData.data:[]);if(!privileged&&getObjectId(user)){const permissionResponse=await fetch(`/api/users/effective-permissions?user=${encodeURIComponent(getObjectId(user))}&business=${encodeURIComponent(nextBusinessId)}`);const permissionData=await permissionResponse.json().catch(()=>({}));const found=(permissionData.data||[]).find(item=>item.module===moduleName);if(found)setPermission(found);}}catch(loadError){setError(loadError.message);}finally{setLoading(false);}},[user,privileged,endpoint,moduleName,title]);
 useEffect(()=>{load();},[load]);useEffect(()=>{if(!notice)return undefined;const timer=setTimeout(()=>setNotice(null),5000);return()=>clearTimeout(timer);},[notice]);
 const filtered=useMemo(()=>{const query=search.trim().toLowerCase();return records.filter(record=>!query||[record.code,record.title,record.meaning,record.category,record.jurisdiction,record.sourceName].some(value=>String(value||"").toLowerCase().includes(query))).sort((a,b)=>a.code.localeCompare(b.code,undefined,{numeric:true,sensitivity:"base"}));},[records,search]);
 const openAdd=()=>{setEditing(null);setForm({...emptyForm,service,jurisdiction:defaultJurisdiction});setShowForm(true);setError("");};
 const openEdit=record=>{setEditing(record);setForm({service:record.service,code:record.code||"",title:record.title||"",meaning:record.meaning||"",category:record.category||"",jurisdiction:record.jurisdiction||"",sourceName:record.sourceName||"",sourceUrl:record.sourceUrl||"",notes:record.notes||"",isActive:record.isActive!==false});setShowForm(true);setError("");};
 const save=async event=>{event.preventDefault();setSaving(true);setError("");try{const response=await fetch(editing?`${endpoint}/${editing._id}`:endpoint,{method:editing?"PUT":"POST",headers:headers({"Content-Type":"application/json"}),body:JSON.stringify({...form,service,jurisdiction:form.jurisdiction||defaultJurisdiction,business:businessId})});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.message||"Failed to save code.");setShowForm(false);setNotice({variant:"success",message:`${form.code} ${editing?"updated":"added"}.`});await load();}catch(saveError){setError(saveError.message);}finally{setSaving(false);}};
 const remove=async record=>{if(!confirm(`Delete ${record.code}?`))return;const response=await fetch(`${endpoint}/${record._id}?business=${encodeURIComponent(businessId)}`,{method:"DELETE",headers:headers()});const data=await response.json().catch(()=>({}));if(!response.ok){setNotice({variant:"danger",message:data.message||"Failed to delete code."});return;}setNotice({variant:"success",message:`${record.code} deleted.`});await load();};
 if(loading)return <div className="operational-codes-loading"><Spinner animation="border"/> Loading sourced codes...</div>;

 return <main className="operational-codes-page"><header className="operational-codes-hero"><div className="operational-codes-hero-icon"><Radio size={34}/></div><div><span>Sourced communications references</span><h1>{title}</h1><p>{subtitle}</p></div><strong>{records.length}<small>stored codes</small></strong>{canCreate?<button type="button" onClick={openAdd}><Plus size={18}/> Add Code</button>:null}</header>
  {notice?<Alert variant={notice.variant} dismissible onClose={()=>setNotice(null)}>{notice.message}</Alert>:null}{error&&!showForm?<Alert variant="danger" dismissible onClose={()=>setError("")}>{error}</Alert>:null}
  {service==="police"?<div className="operational-codes-warning"><ShieldAlert size={20}/><div><strong>Ten-codes are not universal.</strong><span>Meanings vary by department, region, and mutual-aid policy. Verify the selected agency’s current communications plan before operational use.</span></div></div>:<div className="operational-codes-warning marine"><Anchor size={20}/><div><strong>Use current official marine procedures.</strong><span>For distress or safety traffic, follow current USCG, FCC, and international requirements.</span></div></div>}
  <label className="operational-codes-search"><Search size={18}/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder={`Search ${service} codes, meanings, jurisdictions, or sources`}/></label>
  <section className="operational-codes-list">{filtered.map(record=><article key={record._id}><div className="operational-code-mark">{record.code}</div><div className="operational-code-body"><div className="operational-code-heading"><div><span>{record.category}</span><h2>{record.title}</h2></div><div>{record.isSystem?<em>Reference</em>:<em>Custom</em>}{canUpdate?<button onClick={()=>openEdit(record)}>Edit</button>:null}{canDelete&&!record.isSystem?<button className="danger" onClick={()=>remove(record)}>Delete</button>:null}</div></div><p>{record.meaning}</p><dl><div><dt>Jurisdiction</dt><dd>{record.jurisdiction||"Not specified"}</dd></div><div><dt>Source</dt><dd>{record.sourceUrl?<a href={record.sourceUrl} target="_blank" rel="noreferrer">{record.sourceName||"Open source"} <ExternalLink size={13}/></a>:record.sourceName||"Not specified"}</dd></div></dl>{record.notes?<small>{record.notes}</small>:null}</div></article>)}{!filtered.length?<div className="operational-codes-empty">No codes match this search.</div>:null}</section>
  <Modal show={showForm} onHide={()=>!saving&&setShowForm(false)} centered className="operational-code-modal"><Form onSubmit={save}><Modal.Header closeButton><Modal.Title>{editing?"Edit Code":"Add Code"}</Modal.Title></Modal.Header><Modal.Body>{error?<Alert variant="danger">{error}</Alert>:null}<div className="operational-code-form"><Form.Group><Form.Label>Code</Form.Label><Form.Control value={form.code} onChange={event=>setForm(current=>({...current,code:event.target.value}))} required/></Form.Group><Form.Group><Form.Label>Title</Form.Label><Form.Control value={form.title} onChange={event=>setForm(current=>({...current,title:event.target.value}))} required/></Form.Group><Form.Group><Form.Label>Category</Form.Label><Form.Control value={form.category} onChange={event=>setForm(current=>({...current,category:event.target.value}))}/></Form.Group><Form.Group><Form.Label>Jurisdiction</Form.Label><Form.Control value={form.jurisdiction} onChange={event=>setForm(current=>({...current,jurisdiction:event.target.value}))}/></Form.Group><Form.Group className="full"><Form.Label>Meaning</Form.Label><Form.Control as="textarea" rows={3} value={form.meaning} onChange={event=>setForm(current=>({...current,meaning:event.target.value}))} required/></Form.Group><Form.Group><Form.Label>Source Name</Form.Label><Form.Control value={form.sourceName} onChange={event=>setForm(current=>({...current,sourceName:event.target.value}))}/></Form.Group><Form.Group><Form.Label>Source URL</Form.Label><Form.Control type="url" value={form.sourceUrl} onChange={event=>setForm(current=>({...current,sourceUrl:event.target.value}))}/></Form.Group><Form.Group className="full"><Form.Label>Notes</Form.Label><Form.Control as="textarea" rows={2} value={form.notes} onChange={event=>setForm(current=>({...current,notes:event.target.value}))}/></Form.Group></div></Modal.Body><Modal.Footer><Button variant="secondary" onClick={()=>setShowForm(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?"Saving...":editing?"Update Code":"Save Code"}</Button></Modal.Footer></Form></Modal>
 </main>;
}
