import {useEffect,useState} from "react";
import {Alert,Button,Container,Form,Modal,Table} from "react-bootstrap";

const getUserId=()=>{for(const key of ["userInfo","user","authUser","currentUser"]){try{const value=JSON.parse(localStorage.getItem(key)||sessionStorage.getItem(key)||"null");const item=value?.user||value?.data||value;if(item?._id||item?.id)return item._id||item.id;}catch{/* Ignore malformed stored sessions. */}}return "";};
const toDomainCode=value=>String(value||"").trim().toUpperCase().replace(/[^A-Z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,24);
const empty={name:"",code:"",description:"",status:"active"};
export default function DomainsPage(){
 const [domains,setDomains]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[show,setShow]=useState(false),[error,setError]=useState("");
 const load=async()=>{const response=await fetch(`/api/domains?userId=${getUserId()}`,{credentials:"include"});const data=await response.json();if(!response.ok)throw new Error(data.message);setDomains(data.data||[]);};
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load().catch(err=>setError(err.message));},[]);
 const open=domain=>{setEditing(domain||null);setForm(domain?{name:domain.name,code:domain.code,description:domain.description||"",status:domain.status}:empty);setShow(true);};
 const save=async event=>{event.preventDefault();const response=await fetch(editing?`/api/domains/${editing._id}`:"/api/domains",{method:editing?"PUT":"POST",headers:{"Content-Type":"application/json"},credentials:"include",body:JSON.stringify({...form,userId:getUserId()})});const data=await response.json();if(!response.ok){setError(data.message);return;}setShow(false);await load();};
 return <Container fluid className="py-5 px-4"><div className="d-flex justify-content-between align-items-start mb-4"><div><p className="dashboard-section-kicker mb-1">Knowledge configuration</p><h1>Domains</h1><p>Culinary, Writing, Technology, and other broad knowledge areas used in generated IDs.</p></div><Button className="align-self-start" onClick={()=>open(null)}>Add Domain</Button></div>{error&&<Alert variant="danger">{error}</Alert>}<Table responsive hover><thead><tr><th>Name</th><th>Code</th><th>Description</th><th>Status</th><th/></tr></thead><tbody>{domains.map(domain=><tr key={domain._id}><td>{domain.name}</td><td><code>{domain.code}</code></td><td>{domain.description||"—"}</td><td>{domain.status}</td><td><Button size="sm" variant="outline-secondary" onClick={()=>open(domain)}>Edit</Button></td></tr>)}</tbody></Table><Modal show={show} onHide={()=>setShow(false)} centered><Modal.Header closeButton><Modal.Title>{editing?"Edit":"Add"} Domain</Modal.Title></Modal.Header><Modal.Body><Form onSubmit={save}><Form.Group className="mb-3"><Form.Label>Name</Form.Label><Form.Control required value={form.name} onChange={e=>setForm({...form,name:e.target.value,code:toDomainCode(e.target.value)})}/></Form.Group><Form.Group className="mb-3"><Form.Label>Code</Form.Label><Form.Control required readOnly value={form.code}/><Form.Text>Generated automatically from the domain name.</Form.Text></Form.Group><Form.Group className="mb-3"><Form.Label>Description</Form.Label><Form.Control as="textarea" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Form.Group><Form.Select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="archived">Archived</option></Form.Select><div className="text-end mt-3"><Button type="submit">Save Domain</Button></div></Form></Modal.Body></Modal></Container>;
}
