import mongoose from "mongoose";
import Event from "../../models/events/eventModel.js";

const statuses=["Pending","Confirmed","Prep","Completed","Cancelled"];
const payloadFrom=body=>({
 eventName:String(body.eventName||"").trim(),clientName:String(body.clientName||"").trim(),eventDate:body.eventDate,
 eventTime:String(body.eventTime||"").trim(),guestCount:Number(body.guestCount||0),status:statuses.includes(body.status)?body.status:"Pending",
 location:String(body.location||"").trim(),notes:Array.isArray(body.notes)?body.notes.map(String).map(note=>note.trim()).filter(Boolean):[]
});

export const createEvent=async(req,res)=>{try{const payload=payloadFrom(req.body);if(!payload.eventName||!payload.clientName||!payload.eventDate)return res.status(400).json({success:false,message:"Event name, client name, and event date are required"});if(!Number.isFinite(payload.guestCount)||payload.guestCount<0)return res.status(400).json({success:false,message:"Guest count must be zero or greater"});const event=await Event.create(payload);return res.status(201).json({success:true,message:"Event created successfully",event});}catch(error){return res.status(500).json({success:false,message:"Failed to create event",error:error.message});}};
export const getEvents=async(req,res)=>{try{const events=await Event.find().sort({eventDate:1,eventTime:1});return res.json({success:true,count:events.length,events});}catch(error){return res.status(500).json({success:false,message:"Failed to fetch events",error:error.message});}};
export const getEventById=async(req,res)=>{try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid event id"});const event=await Event.findById(req.params.id);if(!event)return res.status(404).json({success:false,message:"Event not found"});return res.json({success:true,event});}catch(error){return res.status(500).json({success:false,message:"Failed to fetch event",error:error.message});}};
export const updateEvent=async(req,res)=>{try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid event id"});const payload=payloadFrom(req.body);if(!payload.eventName||!payload.clientName||!payload.eventDate)return res.status(400).json({success:false,message:"Event name, client name, and event date are required"});const event=await Event.findByIdAndUpdate(req.params.id,payload,{returnDocument:"after",runValidators:true});if(!event)return res.status(404).json({success:false,message:"Event not found"});return res.json({success:true,message:"Event updated successfully",event});}catch(error){return res.status(500).json({success:false,message:"Failed to update event",error:error.message});}};
export const deleteEvent=async(req,res)=>{try{if(!mongoose.Types.ObjectId.isValid(req.params.id))return res.status(400).json({success:false,message:"Invalid event id"});const event=await Event.findByIdAndDelete(req.params.id);if(!event)return res.status(404).json({success:false,message:"Event not found"});return res.json({success:true,message:"Event deleted successfully"});}catch(error){return res.status(500).json({success:false,message:"Failed to delete event",error:error.message});}};
