import {Button} from "react-bootstrap";
import "../../../styles/forms/ChaptersScenesForms.css";
const list=value=>Array.isArray(value)?value:[];
const text=value=>value??"";
function Field({label,value,onChange,type="text",area=false}){return <label className="chapter-field"><span>{label}</span>{area?<textarea rows={3} value={text(value)} onChange={event=>onChange(event.target.value)}/>:<input type={type} value={type==="date"?String(value||"").slice(0,10):text(value)} onChange={event=>onChange(type==="number"?Number(event.target.value||0):event.target.value)}/>}</label>}
function Lines({label,items,onChange}){const rows=list(items);return <section className="chapter-lines"><header><h4>{label}</h4><Button type="button" variant="outline-primary" onClick={()=>onChange([...rows,""])}>Add Line</Button></header>{rows.map((row,index)=><div key={index}><input aria-label={`${label} ${index+1}`} value={text(row)} onChange={event=>onChange(rows.map((item,rowIndex)=>rowIndex===index?event.target.value:item))}/><Button type="button" variant="outline-danger" onClick={()=>onChange(rows.filter((_,rowIndex)=>rowIndex!==index))}>Remove</Button></div>)}</section>}
function Rows({title,items,onChange,blank,children}){const rows=list(items);return <section className="chapter-rows"><header><h3>{title}</h3><Button type="button" variant="outline-primary" onClick={()=>onChange([...rows,blank()])}>Add {title.replace(/s$/i,"")}</Button></header>{rows.map((row,index)=><fieldset key={row?._id||index}><legend>{title.replace(/s$/i,"")} {index+1}</legend>{children(row,(key,next)=>onChange(rows.map((item,rowIndex)=>rowIndex===index?{...item,[key]:next}:item)))}<Button type="button" variant="outline-danger" onClick={()=>onChange(rows.filter((_,rowIndex)=>rowIndex!==index))}>Remove</Button></fieldset>)}</section>}
function Grid({children}){return <div className="chapter-grid">{children}</div>}
function ChapterList({value,onChange}){return <div className="chapter-editor"><Rows title="Chapters" items={value.chapters} onChange={next=>onChange(["chapters"],next)} blank={()=>({chapterNumber:"",chapterTitle:"",summaryOfKeyEvents:"",povMainCharacters:"",wordCount:0})}>{(row,update)=><Grid><Field label="Chapter Number" value={row.chapterNumber} onChange={next=>update("chapterNumber",next)}/><Field label="Chapter Title" value={row.chapterTitle} onChange={next=>update("chapterTitle",next)}/><Field label="Summary of Key Events" value={row.summaryOfKeyEvents} onChange={next=>update("summaryOfKeyEvents",next)} area/><Field label="POV / Main Characters" value={row.povMainCharacters} onChange={next=>update("povMainCharacters",next)}/><Field label="Word Count" value={row.wordCount} onChange={next=>update("wordCount",next)} type="number"/></Grid>}</Rows><Lines label="Notes" items={value.notes} onChange={next=>onChange(["notes"],next)}/></div>}
function ChapterDashboards({value,onChange}){return <div className="chapter-editor"><Rows title="Chapter Dashboards" items={value} onChange={next=>onChange([],next)} blank={()=>({chapterNumberTitle:"",dateWritten:null,wordCount:0,chapterGoalPurpose:"",keyPlotPoints:[],charactersInvolved:[],keyDialogueEvents:[],internalConflictsArcs:[],settings:[],notes:[]})}>{(row,update)=><><Grid><Field label="Chapter Number / Title" value={row.chapterNumberTitle} onChange={next=>update("chapterNumberTitle",next)}/><Field label="Date Written" value={row.dateWritten} onChange={next=>update("dateWritten",next)} type="date"/><Field label="Word Count" value={row.wordCount} onChange={next=>update("wordCount",next)} type="number"/><Field label="Chapter Goal / Purpose" value={row.chapterGoalPurpose} onChange={next=>update("chapterGoalPurpose",next)} area/></Grid>{[["Key Plot Points","keyPlotPoints"],["Characters Involved","charactersInvolved"],["Key Dialogue / Events","keyDialogueEvents"],["Internal Conflicts / Arcs","internalConflictsArcs"],["Settings","settings"],["Notes","notes"]].map(([label,key])=><Lines key={key} label={label} items={row[key]} onChange={next=>update(key,next)}/>)}</>}</Rows></div>}
function ChapterSummary({value,onChange}){return <div className="chapter-editor"><Rows title="Chapter Summaries" items={value.chapters} onChange={next=>onChange(["chapters"],next)} blank={()=>({chapterName:"",summary:""})}>{(row,update)=><Grid><Field label="Chapter Name" value={row.chapterName} onChange={next=>update("chapterName",next)}/><Field label="Summary" value={row.summary} onChange={next=>update("summary",next)} area/></Grid>}</Rows><Lines label="Notes" items={value.notes} onChange={next=>onChange(["notes"],next)}/></div>}
function SceneDashboard({value,onChange}){return <div className="chapter-editor"><Rows title="Scenes" items={value.scenes} onChange={next=>onChange(["scenes"],next)} blank={()=>({scene:"",belongsToChapter:"",settingLocation:"",charactersInvolved:[],keyActionsSummary:[],emotionalImpact:"",notes:[]})}>{(row,update)=><><Grid><Field label="Scene" value={row.scene} onChange={next=>update("scene",next)}/><Field label="Belongs to Chapter" value={row.belongsToChapter} onChange={next=>update("belongsToChapter",next)}/><Field label="Setting / Location" value={row.settingLocation} onChange={next=>update("settingLocation",next)}/><Field label="Emotional Impact" value={row.emotionalImpact} onChange={next=>update("emotionalImpact",next)} area/></Grid><Lines label="Characters Involved" items={row.charactersInvolved} onChange={next=>update("charactersInvolved",next)}/><Lines label="Key Actions / Summary" items={row.keyActionsSummary} onChange={next=>update("keyActionsSummary",next)}/><Lines label="Scene Notes" items={row.notes} onChange={next=>update("notes",next)}/></>}</Rows><Lines label="Notes" items={value.notes} onChange={next=>onChange(["notes"],next)}/></div>}
export default function ChaptersScenesEditor({pageKey,value,onChange}){switch(pageKey){case"chapterList":return <ChapterList value={value} onChange={onChange}/>;case"chapterDashboards":return <ChapterDashboards value={value} onChange={onChange}/>;case"chapterSummary":return <ChapterSummary value={value} onChange={onChange}/>;case"sceneDashboard":return <SceneDashboard value={value} onChange={onChange}/>;default:return null}}
