import {useRef,useState} from "react";
import {Button} from "react-bootstrap";
import "../../../styles/forms/RevisionEditingForms.css";
const list=value=>Array.isArray(value)?value:[];
const text=value=>value??"";
function Field({label,value,onChange,type="text",area=false}){return <label className="revision-field"><span>{label}</span>{area?<textarea rows={3} value={text(value)} onChange={event=>onChange(event.target.value)}/>:<input type={type} value={type==="date"?String(value||"").slice(0,10):text(value)} onChange={event=>onChange(type==="number"?Number(event.target.value||0):event.target.value)}/>}</label>}
function Lines({label,items,onChange}){const rows=list(items);return <section className="revision-lines"><header><h4>{label}</h4><Button type="button" variant="outline-primary" onClick={()=>onChange([...rows,""])}>Add Line</Button></header>{rows.map((row,index)=><div key={index}><input value={text(row)} aria-label={`${label} ${index+1}`} onChange={event=>onChange(rows.map((item,rowIndex)=>rowIndex===index?event.target.value:item))}/><Button type="button" variant="outline-danger" onClick={()=>onChange(rows.filter((_,rowIndex)=>rowIndex!==index))}>Remove</Button></div>)}</section>}
function RevisionNotes({value,onChange}){const rows=list(value.revisionNotes);return <div className="revision-editor"><section className="revision-rows"><header><h3>Revision Notes</h3><Button type="button" variant="outline-primary" onClick={()=>onChange(["revisionNotes"],[...rows,{pageNumber:"",revisionNote:""}])}>Add Note</Button></header>{rows.map((row,index)=><fieldset key={row._id||index}><legend>Revision Note {index+1}</legend><div className="revision-grid"><Field label="Page Number" value={row.pageNumber} onChange={next=>onChange(["revisionNotes"],rows.map((item,rowIndex)=>rowIndex===index?{...item,pageNumber:next}:item))}/><Field label="Revision Note" value={row.revisionNote} onChange={next=>onChange(["revisionNotes"],rows.map((item,rowIndex)=>rowIndex===index?{...item,revisionNote:next}:item))} area/></div><Button type="button" variant="outline-danger" onClick={()=>onChange(["revisionNotes"],rows.filter((_,rowIndex)=>rowIndex!==index))}>Remove</Button></fieldset>)}</section><Lines label="Notes" items={value.notes} onChange={next=>onChange(["notes"],next)}/></div>}
const revisionGroups=[["Plot & Structure","plotStructure"],["Character Development","characterDevelopment"],["Setting & World-Building","settingWorldBuilding"]];
const authorialGroups=[["Pre-Writing Phase","preWritingPhase"],["Writing Phase","writingPhase"],["Research & Inspiration","researchInspiration"],["Feedback & Revision","feedbackRevision"],["Publishing Preparation","publishingPreparation"],["Marketing & Launch","marketingLaunch"],["Mindset & Motivation","mindsetMotivation"]];
function ProjectInfo({value,onChange}){const info=value.projectInfo||{};const fileRef=useRef(null);let book={};try{book=JSON.parse(localStorage.getItem("activePlannerBook")||"{}")}catch{}const genre=info.genre||book.genre||book.genres?.[0]||"";const words=info.expectedWordCount||book.targetWords||0;const set=(key,next)=>onChange(["projectInfo",key],next);return <section className="revision-project"><h3>Project Information</h3><div className="revision-grid"><Field label="Project Title" value={info.projectTitle||book.title} onChange={next=>set("projectTitle",next)}/><Field label="Date Started" value={info.dateStarted} onChange={next=>set("dateStarted",next)} type="date"/><Field label="Date Completed" value={info.dateCompleted} onChange={next=>set("dateCompleted",next)} type="date"/><Field label="Theme" value={info.theme} onChange={next=>set("theme",next)}/><Field label="Genre" value={genre} onChange={next=>set("genre",next)}/><Field label="Expected Word Count" value={words} onChange={next=>set("expectedWordCount",next)} type="number"/><div className="revision-field revision-image-field"><span>Image</span><div><input type="file" accept="image/*" ref={fileRef} onChange={event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>set("imageUrl",reader.result);reader.readAsDataURL(file)}}/><Button type="button" variant="outline-danger" onClick={()=>{set("imageUrl","");if(fileRef.current)fileRef.current.value=""}}>Clear</Button>{info.imageUrl?<img src={info.imageUrl} alt="Project preview"/>:null}</div></div></div></section>}
function ChecklistGroup({title,items,onChange}){const rows=list(items);return <section className="revision-checklist"><header><h3>{title}</h3></header>{rows.map((row,index)=><fieldset key={row._id||index}><legend>Item {index+1}</legend><div className="revision-grid"><div className="revision-question"><span>Question</span><p>{text(row.question)||"—"}</p></div><label className="revision-field"><span>Status</span><select value={text(row.status)} onChange={event=>onChange(rows.map((item,rowIndex)=>rowIndex===index?{...item,status:event.target.value}:item))}><option value="">Select Status</option><option>Yes</option><option>No</option><option>Not Sure</option><option>Needs Improvement</option></select></label></div></fieldset>)}</section>}
function Checklist({value,onChange,groups}){const [active,setActive]=useState(0);const [title,key]=groups[active]||groups[0]||[];return <div className="revision-editor"><ProjectInfo value={value} onChange={onChange}/><nav className="revision-tabs" aria-label="Checklist phases">{groups.map(([tabTitle],index)=><button type="button" className={index===active?"active":""} key={tabTitle} onClick={()=>setActive(index)}>{tabTitle}</button>)}</nav>{title&&<ChecklistGroup title={title} items={value[key]} onChange={next=>onChange([key],next)}/>}<Lines label="Notes" items={value.notes} onChange={next=>onChange(["notes"],next)}/></div>}
export default function RevisionEditingEditor({pageKey,value,onChange}){switch(pageKey){case"revisionNotes":return <RevisionNotes value={value} onChange={onChange}/>;case"revisionChecklist":return <Checklist value={value} onChange={onChange} groups={revisionGroups}/>;case"authorialChecklist":return <Checklist value={value} onChange={onChange} groups={authorialGroups}/>;default:return null}}
