import {useCallback,useEffect,useMemo,useState} from "react";
import {Button,Card,Container,Form,Modal,Table} from "react-bootstrap";
import Alert from "../../components/PopupAlert.jsx";
import CostingForm from "../forms/admin/catalog/CostingForm.jsx";

const id=value=>typeof value==="string"?value:String(value?._id||"");
const list=(data,key)=>Array.isArray(data?.[key])?data[key]:Array.isArray(data?.data)?data.data:Array.isArray(data)?data:[];
const sources=[["/api/products","products"],["/api/ingredients","ingredients"],["/api/reference/statuses","statuses"],["/api/reference/metric-units","metricUnits"],["/api/reference/imperial-units","imperialUnits"]];

export default function Costings(){
 const [rows,setRows]=useState([]),[lookups,setLookups]=useState({products:[],ingredients:[],statuses:[],metricUnits:[],imperialUnits:[]});
 const [query,setQuery]=useState(""),[selected,setSelected]=useState(null),[show,setShow]=useState(false),[deleting,setDeleting]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);setError("");const responses=await Promise.all([fetch("/api/costings"),...sources.map(([url])=>fetch(url))]);const data=await Promise.all(responses.map(response=>response.json().catch(()=>null)));const failed=responses.findIndex(response=>!response.ok);if(failed>=0)throw new Error(data[failed]?.message||"Costing data could not load.");setRows(list(data[0],"costings"));const next={};sources.forEach(([,key],index)=>{next[key]=list(data[index+1],key);});setLookups(next);}catch(err){setError(err.message);}finally{setLoading(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer);},[load]);
 const visible=useMemo(()=>rows.filter(row=>[row.name,row.slug,row.product?.name].some(value=>String(value||"").toLowerCase().includes(query.toLowerCase()))),[query,rows]);
 const save=async payload=>{try{setSaving(true);setError("");const response=await fetch(selected?`/api/costings/${id(selected)}`:"/api/costings",{method:selected?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"Costing could not save.");setShow(false);setSelected(null);setMessage("Costing saved and totals recalculated.");await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
 const remove=async()=>{try{setSaving(true);const response=await fetch(`/api/costings/${id(selected)}`,{method:"DELETE"});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"Costing could not delete.");setDeleting(false);setSelected(null);setMessage("Costing deleted.");await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
 return <Container fluid className="py-4"><div className="d-flex justify-content-between gap-3 mb-3"><div><h1>Costings</h1><p className="text-muted">Build ingredient costings and save calculated totals to MongoDB.</p></div><Button onClick={()=>{setSelected(null);setShow(true);}}>Add Costing</Button></div>{message&&<Alert variant="success" dismissible onClose={()=>setMessage("")}>{message}</Alert>}{error&&<Alert variant="danger" dismissible onClose={()=>setError("")}>{error}</Alert>}<Card className="border-0 shadow-sm"><Card.Body><Form.Control className="mb-3" placeholder="Search costings" value={query} onChange={e=>setQuery(e.target.value)}/><Table responsive hover><thead><tr><th>Name</th><th>Product</th><th>Batch yield</th><th>Material</th><th>Total</th><th>Unit cost</th><th>Suggested price</th><th>Status</th><th></th></tr></thead><tbody>{loading&&<tr><td colSpan="9">Loading...</td></tr>}{!loading&&visible.length===0&&<tr><td colSpan="9">No costings found.</td></tr>}{visible.map(row=><tr key={row._id}><td>{row.name}</td><td>{row.product?.name||"—"}</td><td>{row.batchYield||"—"}</td><td>${Number(row.materialCost||0).toFixed(2)}</td><td>${Number(row.totalCost||0).toFixed(2)}</td><td>${Number(row.unitCost||0).toFixed(2)}</td><td>{row.suggestedPrice?`$${Number(row.suggestedPrice).toFixed(2)}`:"—"}</td><td>{row.status?.name||"—"}</td><td className="text-end text-nowrap"><Button size="sm" variant="outline-primary" className="me-2" onClick={()=>{setSelected(row);setShow(true);}}>Edit</Button><Button size="sm" variant="outline-danger" onClick={()=>{setSelected(row);setDeleting(true);}}>Delete</Button></td></tr>)}</tbody></Table></Card.Body></Card>
 <Modal show={show} onHide={()=>setShow(false)} fullscreen="lg-down" size="xl"><Modal.Header closeButton><Modal.Title>{selected?"Edit":"Add"} Costing</Modal.Title></Modal.Header><Modal.Body><CostingForm key={id(selected)||"new"} initialData={selected||{}} lookups={lookups} onSubmit={save} saving={saving}/></Modal.Body></Modal><Modal show={deleting} onHide={()=>setDeleting(false)}><Modal.Header closeButton><Modal.Title>Delete costing</Modal.Title></Modal.Header><Modal.Body>Delete <strong>{selected?.name}</strong>?</Modal.Body><Modal.Footer><Button variant="secondary" onClick={()=>setDeleting(false)}>Cancel</Button><Button variant="danger" onClick={remove} disabled={saving}>Delete</Button></Modal.Footer></Modal></Container>;
}
