import {useCallback,useEffect,useMemo,useState} from "react";
import {Button,Card,Container,Form,Modal,Table} from "react-bootstrap";
import Alert from "../../components/PopupAlert.jsx";
import IngredientForm from "../forms/admin/catalog/IngredientForm.jsx";

const id=value=>typeof value==="string"?value:String(value?._id||"");
const list=(data,key)=>Array.isArray(data?.[key])?data[key]:Array.isArray(data?.data)?data.data:Array.isArray(data)?data:[];
const endpoints=[["/api/reference/parts","parts"],["/api/reference/forms","forms"],["/api/reference/metric-units","metricUnits"],["/api/reference/imperial-units","imperialUnits"],["/api/reference/statuses","statuses"]];

export default function Ingredients(){
 const [rows,setRows]=useState([]),[lookups,setLookups]=useState({parts:[],forms:[],metricUnits:[],imperialUnits:[],statuses:[]});
 const [query,setQuery]=useState(""),[selected,setSelected]=useState(null),[show,setShow]=useState(false),[deleting,setDeleting]=useState(false),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=useCallback(async()=>{try{setLoading(true);setError("");const urls=["/api/ingredients",...endpoints.map(([url])=>url)];const responses=await Promise.all(urls.map(url=>fetch(url)));const data=await Promise.all(responses.map(response=>response.json().catch(()=>null)));const failed=responses.findIndex(response=>!response.ok);if(failed>=0)throw new Error(data[failed]?.message||"Ingredient data could not load.");setRows(list(data[0],"ingredients"));const next={};endpoints.forEach(([,key],index)=>{next[key]=list(data[index+1],key);});setLookups(next);}catch(err){setError(err.message);}finally{setLoading(false);}},[]);
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer);},[load]);
 const visible=useMemo(()=>rows.filter(row=>[row.name,row.botanicalName,row.inciName,row.slug].some(value=>String(value||"").toLowerCase().includes(query.toLowerCase()))),[query,rows]);
 const save=async payload=>{try{setSaving(true);const response=await fetch(selected?`/api/ingredients/${id(selected)}`:"/api/ingredients",{method:selected?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"Ingredient could not save.");setShow(false);setSelected(null);setMessage("Ingredient saved.");await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
 const remove=async()=>{try{setSaving(true);const response=await fetch(`/api/ingredients/${id(selected)}`,{method:"DELETE"});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"Ingredient could not delete.");setDeleting(false);setSelected(null);setMessage("Ingredient deleted.");await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
 return <Container fluid className="py-4"><div className="d-flex justify-content-between gap-3 mb-3"><div><h1>Ingredients</h1><p className="text-muted">Manage ingredients and all model-backed reference selections.</p></div><Button onClick={()=>{setSelected(null);setShow(true);}}>Add Ingredient</Button></div>{message&&<Alert variant="success" dismissible onClose={()=>setMessage("")}>{message}</Alert>}{error&&<Alert variant="danger" dismissible onClose={()=>setError("")}>{error}</Alert>}<Card className="border-0 shadow-sm"><Card.Body><Form.Control className="mb-3" placeholder="Search ingredients" value={query} onChange={e=>setQuery(e.target.value)}/><Table responsive hover><thead><tr><th>Name</th><th>Botanical / INCI</th><th>Part</th><th>Form</th><th>Units</th><th>Status</th><th></th></tr></thead><tbody>{loading&&<tr><td colSpan="7">Loading...</td></tr>}{!loading&&visible.length===0&&<tr><td colSpan="7">No ingredients found.</td></tr>}{visible.map(row=><tr key={row._id}><td>{row.name}</td><td>{row.botanicalName||row.inciName||"—"}</td><td>{row.part?.name||"—"}</td><td>{row.form?.name||"—"}</td><td>{row.metricUnit?.symbol||"—"} / {row.imperialUnit?.symbol||"—"}</td><td>{row.status?.name||"—"}</td><td className="text-end"><Button size="sm" variant="outline-primary" className="me-2" onClick={()=>{setSelected(row);setShow(true);}}>Edit</Button><Button size="sm" variant="outline-danger" onClick={()=>{setSelected(row);setDeleting(true);}}>Delete</Button></td></tr>)}</tbody></Table></Card.Body></Card>
 <Modal show={show} onHide={()=>setShow(false)} size="xl"><Modal.Header closeButton><Modal.Title>{selected?"Edit":"Add"} Ingredient</Modal.Title></Modal.Header><Modal.Body><IngredientForm key={id(selected)||"new"} initialData={selected||{}} lookups={lookups} onSubmit={save} saving={saving}/></Modal.Body></Modal><Modal show={deleting} onHide={()=>setDeleting(false)}><Modal.Header closeButton><Modal.Title>Delete ingredient</Modal.Title></Modal.Header><Modal.Body>Delete <strong>{selected?.name}</strong>?</Modal.Body><Modal.Footer><Button variant="secondary" onClick={()=>setDeleting(false)}>Cancel</Button><Button variant="danger" onClick={remove} disabled={saving}>Delete</Button></Modal.Footer></Modal></Container>;
}
