import {useCallback,useEffect,useState} from "react";
import {Button,Container,Modal,Table} from "react-bootstrap";
import Alert from "../../components/PopupAlert.jsx";
import LocationForm from "../forms/admin/catalog/LocationForm.jsx";
const id=value=>typeof value==="string"?value:String(value?._id||value?.id||"");
const list=data=>Array.isArray(data)?data:Array.isArray(data?.data)?data.data:Array.isArray(data?.businesses)?data.businesses:[];
export default function Locations(){
 const [rows,setRows]=useState([]),[businesses,setBusinesses]=useState([]),[types,setTypes]=useState([]),[selected,setSelected]=useState(null),[show,setShow]=useState(false),[confirm,setConfirm]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const responses=await Promise.all([fetch("/api/locations"),fetch("/api/location-types"),fetch("/api/businesses")]);const data=await Promise.all(responses.map(response=>response.json().catch(()=>null)));const failed=responses.findIndex(response=>!response.ok);if(failed>=0)throw new Error(data[failed]?.message||"Location data could not load.");setRows(list(data[0]));setTypes(list(data[1]));setBusinesses(list(data[2]));}catch(err){setError(err.message);}},[]);
 useEffect(()=>{const timer=window.setTimeout(load,0);return()=>window.clearTimeout(timer);},[load]);
 const save=async payload=>{try{setSaving(true);const response=await fetch(selected?`/api/locations/${id(selected)}`:"/api/locations",{method:selected?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"Location could not save.");setShow(false);setSelected(null);await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
 const remove=async()=>{try{setSaving(true);const response=await fetch(`/api/locations/${id(selected)}`,{method:"DELETE"});const data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.message||"Location could not delete.");setConfirm(false);setSelected(null);await load();}catch(err){setError(err.message);}finally{setSaving(false);}};
 return <Container fluid className="py-4"><div className="d-flex justify-content-between mb-3"><div><h1>Locations</h1><p className="text-muted">Manage business locations and parent location relationships.</p></div><Button onClick={()=>{setSelected(null);setShow(true);}}>Add Location</Button></div>{error&&<Alert variant="danger" dismissible onClose={()=>setError("")}>{error}</Alert>}<Table responsive hover><thead><tr><th>Name</th><th>Code</th><th>Business</th><th>Type</th><th>Parent</th><th>Status</th><th></th></tr></thead><tbody>{rows.length===0&&<tr><td colSpan="7">No locations found.</td></tr>}{rows.map(row=><tr key={row._id}><td>{row.name}</td><td>{row.code||"—"}</td><td>{row.business?.legalName||row.business?.name||"—"}</td><td>{row.type?.name||"—"}</td><td>{row.parentLocation?.name||"—"}</td><td>{row.isActive?"Active":"Inactive"}</td><td className="text-end"><Button size="sm" variant="outline-primary" className="me-2" onClick={()=>{setSelected(row);setShow(true);}}>Edit</Button><Button size="sm" variant="outline-danger" onClick={()=>{setSelected(row);setConfirm(true);}}>Delete</Button></td></tr>)}</tbody></Table><Modal show={show} onHide={()=>setShow(false)} size="lg"><Modal.Header closeButton><Modal.Title>{selected?"Edit":"Add"} Location</Modal.Title></Modal.Header><Modal.Body><LocationForm key={id(selected)||"new"} initialData={selected||{}} businesses={businesses} types={types} locations={rows} onSubmit={save} saving={saving}/></Modal.Body></Modal><Modal show={confirm} onHide={()=>setConfirm(false)}><Modal.Header closeButton><Modal.Title>Delete location</Modal.Title></Modal.Header><Modal.Body>Delete <strong>{selected?.name}</strong>?</Modal.Body><Modal.Footer><Button onClick={()=>setConfirm(false)}>Cancel</Button><Button variant="danger" onClick={remove}>Delete</Button></Modal.Footer></Modal></Container>;
}
