import "../../../styles/forms/ChaptersScenesForms.css";
const rows=value=>Array.isArray(value)?value.filter(item=>item!==null&&item!==undefined&&item!==""):[];
const show=value=>value===null||value===undefined||value===""?"—":String(value);
function Lines({items}){const values=rows(items);return values.length?<ul>{values.map((item,index)=><li key={index}>{show(item)}</li>)}</ul>:<p>—</p>}
function Facts({items}){return <dl className="chapter-view-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl>}
function Block({title,children}){return <section className="chapter-view-block"><h4>{title}</h4>{children}</section>}
function ChapterListView({data}){return <div className="chapter-view"><section className="chapter-view-table"><h3>Chapter List</h3><div className="chapter-view-table-head chapter-list-columns"><span>Number</span><span>Title</span><span>Key Events</span><span>POV / Main Characters</span><span>Word Count</span></div>{rows(data.chapters).map((row,index)=><div className="chapter-view-table-row chapter-list-columns" key={row._id||index}><span>{show(row.chapterNumber)}</span><span>{show(row.chapterTitle)}</span><span>{show(row.summaryOfKeyEvents)}</span><span>{show(row.povMainCharacters)}</span><span>{Number(row.wordCount||0).toLocaleString()}</span></div>)}</section><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function DashboardsView({data}){return <div className="chapter-view chapter-view-grid">{rows(data).map((row,index)=><article className="chapter-view-card" key={row._id||index}><header><p>Chapter Dashboard {index+1}</p><h3>{show(row.chapterNumberTitle)}</h3></header><Facts items={[["Date Written",row.dateWritten?new Date(row.dateWritten).toLocaleDateString():"—"],["Word Count",Number(row.wordCount||0).toLocaleString()],["Goal / Purpose",row.chapterGoalPurpose]]}/>{[["Key Plot Points","keyPlotPoints"],["Characters Involved","charactersInvolved"],["Key Dialogue / Events","keyDialogueEvents"],["Internal Conflicts / Arcs","internalConflictsArcs"],["Settings","settings"],["Notes","notes"]].map(([title,key])=><Block key={key} title={title}><Lines items={row[key]}/></Block>)}</article>)}</div>}
function SummaryView({data}){return <div className="chapter-view"><section className="chapter-view-table"><h3>Chapter Summaries</h3><div className="chapter-view-table-head chapter-summary-columns"><span>Chapter</span><span>Summary</span></div>{rows(data.chapters).map((row,index)=><div className="chapter-view-table-row chapter-summary-columns" key={row._id||index}><span>{show(row.chapterName)}</span><span>{show(row.summary)}</span></div>)}</section><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function ScenesView({data}){return <div className="chapter-view chapter-view-grid">{rows(data.scenes).map((row,index)=><article className="chapter-view-card" key={row._id||index}><header><p>Scene {index+1}</p><h3>{show(row.scene)}</h3></header><Facts items={[["Chapter",row.belongsToChapter],["Setting / Location",row.settingLocation],["Emotional Impact",row.emotionalImpact]]}/><Block title="Characters Involved"><Lines items={row.charactersInvolved}/></Block><Block title="Key Actions / Summary"><Lines items={row.keyActionsSummary}/></Block><Block title="Notes"><Lines items={row.notes}/></Block></article>)}<Block title="General Notes"><Lines items={data.notes}/></Block></div>}
export default function ChaptersScenesView({pageKey,data}){switch(pageKey){case"chapterList":return <ChapterListView data={data}/>;case"chapterDashboards":return <DashboardsView data={data}/>;case"chapterSummary":return <SummaryView data={data}/>;case"sceneDashboard":return <ScenesView data={data}/>;default:return null}}
