import "../../../styles/forms/NotesExtrasForms.css";
const rows=value=>Array.isArray(value)?value.filter(item=>item!==null&&item!==undefined&&item!==""):[];
const show=value=>value===null||value===undefined||value===""?"—":String(value);
const date=value=>value?new Date(value).toLocaleDateString():"—";
function Lines({items}){const values=rows(items);return values.length?<ul>{values.map((item,index)=><li key={index}>{show(item)}</li>)}</ul>:<p>—</p>}
function Facts({items}){return <dl className="extras-view-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl>}
function Block({title,children}){return <section className="extras-view-block"><h3>{title}</h3>{children}</section>}
function Cards({title,items,children}){return <Block title={title}><div className="extras-view-cards">{rows(items).map((row,index)=><article key={row._id||index}>{children(row,index)}</article>)}</div></Block>}
function Notes({data}){return <Block title="Notes"><Lines items={data.notes}/></Block>}
function Brainstorm({data}){const categories=data.ideaCategories||{};return <div className="extras-view"><Block title="Idea Dump"><Lines items={data.ideaDump}/></Block><div className="extras-view-columns">{[["Plot Twists","plotTwists"],["Character Moments","characterMoments"],["Scene Concepts","sceneConcepts"],["Dialogue Snippets","dialogueSnippets"]].map(([title,key])=><Block key={key} title={title}><Lines items={categories[key]}/></Block>)}</div><Block title="Ideas to Explore More Deeply"><Lines items={data.ideasToExploreMoreDeeply}/></Block><Notes data={data}/></div>}
function Feedback({data}){return <div className="extras-view"><Cards title="Feedback Log" items={data.feedback}>{row=><><Facts items={[["Date",date(row.date)],["From",row.from],["Section / Chapter",row.sectionChapter],["Feedback Summary",row.feedbackSummary],["Actions to Take",row.actionsToTake]]}/><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
function Publishing({data}){return <div className="extras-view"><Facts items={[["Type of Publishing",data.typeOfPublishing],["Why This Path",data.whyThisPath],["Total Budget",Number(data.totalBudget||0).toLocaleString()]]}/><Block title="To-Do List"><Lines items={data.toDoList}/></Block><Cards title="Publishing Timeline" items={data.publishingTimeline}>{row=><><Facts items={[["Step",row.step],["Target Date",date(row.targetDate)],["Status",row.status]]}/><Lines items={row.notes}/></>}</Cards><Block title="Distribution Platforms"><Lines items={data.distributionPlatforms}/></Block><Cards title="Budget Overview" items={data.budgetOverview}>{row=><><Facts items={[["Task",row.task],["Estimated Cost",Number(row.estimatedCost||0).toLocaleString()],["Actual Cost",Number(row.actualCost||0).toLocaleString()],["Paid Status",row.paidStatus]]}/><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
function Marketing({data}){return <div className="extras-view"><Block title="Brainstorm Zone"><Lines items={data.brainstormZone}/></Block>{[["Digital Marketing","digitalMarketing"],["Community Outreach","communityOutreach"]].map(([title,key])=><Cards key={key} title={title} items={data[key]}>{row=><><Facts items={[["Idea",row.idea],["Where / Who",row.whereWho],["Status",row.status]]}/><Lines items={row.notes}/></>}</Cards>)}<Cards title="Promotional Ideas" items={data.promotionalIdeas}>{row=><><Facts items={[["Idea",row.idea],["Cost",Number(row.cost||0).toLocaleString()],["Description",row.description],["Deadline",date(row.deadline)]]}/><Lines items={row.notes}/></>}</Cards><Cards title="Execution Timeline" items={data.timelineForExecution}>{row=><><Facts items={[["Step",row.marketingStep],["Start",date(row.startDate)],["End",date(row.endDate)],["Status",row.status]]}/><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
function Backup({data}){return <div className="extras-view"><Cards title="File Inventory" items={data.fileInventory}>{row=><><Facts items={[["File Name",row.fileName],["Type",row.type],["Description",row.description],["Last Edited",date(row.lastEdited)]]}/><Lines items={row.notes}/></>}</Cards><Cards title="Backup Locations" items={data.backupLocations}>{row=><><Facts items={[["File Name",row.fileName],["Location / Service",row.locationService],["Backup Date",date(row.backupDate)],["Method",row.method]]}/><Lines items={row.notes}/></>}</Cards><Cards title="Backup Schedule" items={data.backupSchedule}>{row=><><Facts items={[["Frequency",row.frequency],["Task",row.task],["Responsible",row.responsible],["Next Due",date(row.nextDueDate)]]}/><Lines items={row.notes}/></>}</Cards><div className="extras-view-columns"><Block title="Backup Checklist"><Lines items={data.backupChecklist}/></Block><Block title="Custom Checklist"><Lines items={data.customBackupChecklist}/></Block></div><Notes data={data}/></div>}
function MindMap({data}){return <div className="extras-view"><Block title="Main Idea"><p>{show(data.mainIdea)}</p></Block><Cards title="Mind Map Nodes" items={data.nodes}>{row=><><Facts items={[["Label",row.label],["Text",row.text],["Parent Key",row.parentKey],["Node Key",row.nodeKey],["Sort Order",row.sortOrder]]}/><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
function Quotes({data}){return <div className="extras-view"><Cards title="Quotes Collection" items={data.quotes}>{row=><><blockquote>{show(row.quote)}</blockquote><Facts items={[["Author / Source",row.authorSource]]}/><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
function NotesPages({data}){return <div className="extras-view"><Block title="Lined Notes"><Lines items={data.linedNotes}/></Block><Block title="Dotted Notes"><p>{show(data.dottedNotes)}</p></Block><Block title="Grid Notes"><p>{show(data.gridNotes)}</p></Block><Notes data={data}/></div>}
export default function NotesExtrasView({pageKey,data}){switch(pageKey){case"brainstormingIdeas":return <Brainstorm data={data}/>;case"feedbackLog":return <Feedback data={data}/>;case"publishingPlan":return <Publishing data={data}/>;case"marketingIdeas":return <Marketing data={data}/>;case"backupLogFileTracker":return <Backup data={data}/>;case"mindMap":return <MindMap data={data}/>;case"quotesCollection":return <Quotes data={data}/>;case"notesPages":return <NotesPages data={data}/>;default:return null}}
