import "../../../styles/forms/PlotStructureForms.css";

const rows=value=>Array.isArray(value)?value.filter(item=>item!==null&&item!==undefined&&item!==""):[];
const show=value=>value===null||value===undefined||value===""?"—":String(value);
const heading=key=>key.replace(/([A-Z])/g," $1").replace(/^./,letter=>letter.toUpperCase());
function Lines({items}){const values=rows(items);return values.length?<ul>{values.map((item,index)=><li key={item?._id||index}>{show(typeof item==="object"?item.text:item)}</li>)}</ul>:<p>—</p>}
function Facts({items}){return <dl className="plot-view-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl>}
function Block({title,children}){return <section className="plot-view-block"><h4>{title}</h4>{children}</section>}
function ListBlocks({data,keys}){return <div className="plot-view-columns">{keys.map(key=><Block key={key} title={heading(key)}><Lines items={data?.[key]}/></Block>)}</div>}
function Table({title,columns,items}){const columnClass=`plot-view-columns-${columns.length}`;return <section className="plot-view-table"><h3>{title}</h3><div className={`plot-view-table-head ${columnClass}`}>{columns.map(([label])=><span key={label}>{label}</span>)}</div>{rows(items).map((item,index)=><div className={`plot-view-table-row ${columnClass}`} key={item._id||index}>{columns.map(([label,key])=><span key={key}>{show(item[key])}</span>)}</div>)}</section>}

function StoryOutlineView({data}){return <div className="plot-view"><article className="plot-view-card"><Facts items={[["Story Title",data.storyTitle],["Main Story Goal / Premise",data.mainStoryGoalPremise]]}/><Table title="Act Structure Summary" columns={[["Act","act"],["Key Events / Purpose","keyEventsPurpose"]]} items={data.actStructureSummary}/><Table title="Major Plot Points" columns={[["Stage","stage"],["Event / Turning Point","eventTurningPoint"]]} items={data.majorPlotPoints}/><ListBlocks data={data} keys={["subplotsConnections","notesIdeas","notes"]}/></article></div>}
function IntroductionView({data}){return <div className="plot-view"><ListBlocks data={data} keys={["introductionNotes","notes"]}/></div>}
function IncitingIncidentView({data}){return <div className="plot-view"><article className="plot-view-card"><Facts items={[["What Disrupts the Ordinary World",data.whatHappensThatDisruptsOrdinaryWorld],["External or Internal Cause",data.externalOrInternalCause],["Protagonist's Initial Reaction",data.protagonistInitialReaction],["New Question or Problem",data.newQuestionOrProblemIntroduced],["When the Event Occurs",data.whenEventOccurs],["How Long the Effect Lasts",data.howLongEffectLasts]]}/><ListBlocks data={data} keys={["connectionToMainConflict","notes"]}/></article></div>}
function KeyPlotPointsView({data}){return <div className="plot-view"><Table title="Key Plot Points" columns={[["Plot Point","plotPointName"],["What Happens","descriptionWhatHappens"],["Chapter / Act","chapterAct"],["Effect on Characters or Story","effectOnCharactersOrStory"]]} items={data.plotPoints}/><ListBlocks data={data} keys={["additionalNotes","notes"]}/></div>}
function EventListView({title,data}){return <div className="plot-view"><article className="plot-view-card"><Block title={`${title} Events`}><Lines items={data.events}/></Block><Block title="Notes"><Lines items={data.notes}/></Block></article></div>}
function SubplotsView({data}){return <div className="plot-view"><Table title="Subplots" columns={[["Number","subplotNumber"],["Title","subplotTitle"],["Characters","characters"],["Connection to Main Plot","connectionToMainPlot"],["Beginning","beginning"],["Development","development"],["Resolution","resolution"]]} items={data.subplots}/><ListBlocks data={data} keys={["notesIdeas","notes"]}/></div>}
function EpilogueView({data}){return <div className="plot-view"><article className="plot-view-card"><Block title="Epilogue Snapshot"><Facts items={[["Time Jump",data.epilogueSnapshot?.timeJump],["Setting",data.epilogueSnapshot?.settingOfEpilogue]]}/></Block><Block title="Character Updates"><Facts items={[["Protagonist",data.characterUpdates?.protagonist],["Supporting Characters",data.characterUpdates?.supportingCharacters],["Antagonist",data.characterUpdates?.antagonist]]}/></Block><Block title="Main Message or Closure"><p>{show(data.mainMessageOrClosure)}</p></Block><ListBlocks data={data} keys={["optionalElements","notes"]}/></article></div>}
function ForeshadowingView({data}){return <div className="plot-view"><article className="plot-view-card"><Facts items={[["Foreshadowing Element",data.foreshadowingElement],["Scene / Chapter",data.sceneChapter],["Page / Paragraph",data.pageParagraph],["Subtlety Level",data.subtletyLevel]]}/><ListBlocks data={data} keys={["whatItForeshadows","whereAndHowTwistHappens","notesConnections","notes"]}/></article></div>}
function ConflictsView({data}){return <div className="plot-view"><Table title="Conflict Resolution" columns={[["Conflict","conflict"],["Characters Involved","charactersInvolved"],["How It Is Resolved","howIsItResolved"],["Outcome / Impact","outcomeImpact"]]} items={data.conflicts}/><Block title="Final Reflection"><p>{show(data.finalReflection)}</p></Block><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function LessonsView({data}){return <div className="plot-view"><Table title="Lessons Learned" columns={[["Character / Group","characterGroup"],["What They Learned or Realized","whatDidTheyLearnOrRealize"],["How This Changed Them","howDidThisChangeThem"]]} items={data.lessons}/><ListBlocks data={data} keys={["overallMessageMoral","notes"]}/></div>}
function OpeningLinesView({data}){return <div className="plot-view"><article className="plot-view-card"><ListBlocks data={data} keys={["openingLineGoals","brainstormLines"]}/><Block title="Top Choice / Final Draft"><p>{show(data.topChoiceFinalDraft)}</p></Block><Block title="Notes"><Lines items={data.notes}/></Block></article></div>}
function QuestionsView({data,groups}){return <div className="plot-view">{groups.map(group=><section className="plot-view-questions" key={group}><h3>{heading(group)}</h3>{rows(data[group]).map((item,index)=><article key={item._id||index}><h4>{show(item.question)}</h4><p>{show(item.response)}</p></article>)}</section>)}<Block title="Notes"><Lines items={data.notes}/></Block></div>}
function ActView({data,groups}){return <div className="plot-view">{groups.map(([key,title,fields])=><article className="plot-view-card" key={key}><header><h3>{title}</h3></header><Facts items={fields.map(field=>[heading(field),data[key]?.[field]])}/></article>)}<Block title="Notes"><Lines items={data.notes}/></Block></div>}
function ActWritingPagesView({data}){return <div className="plot-view plot-view-grid">{rows(data).map((item,index)=><article className="plot-view-card" key={item._id||index}><header><p>Act Writing Page {index+1}</p><h3>{show(item.sceneNumberName)}</h3></header><Facts items={[["Act",item.act],["Setting",item.setting],["Characters",item.characters],["Scene Summary",item.sceneSummary]]}/><ListBlocks data={item} keys={["writingNotes","notes"]}/></article>)}</div>}

export default function PlotStructureView({pageKey,data}){switch(pageKey){case"storyOutline":return <StoryOutlineView data={data}/>;case"introduction":return <IntroductionView data={data}/>;case"incitingIncident":return <IncitingIncidentView data={data}/>;case"keyPlotPoints":return <KeyPlotPointsView data={data}/>;case"risingActions":return <EventListView title="Rising Action" data={data}/>;case"fallingActions":return <EventListView title="Falling Action" data={data}/>;case"climax":return <EventListView title="Climax" data={data}/>;case"resolution":return <EventListView title="Resolution" data={data}/>;case"subplotOverview":return <SubplotsView data={data}/>;case"epilogue":return <EpilogueView data={data}/>;case"foreshadowing":return <ForeshadowingView data={data}/>;case"conflictResolution":return <ConflictsView data={data}/>;case"lessonsLearned":return <LessonsView data={data}/>;case"openingLineBrainstorm":return <OpeningLinesView data={data}/>;case"questionsThatCanHelp":return <QuestionsView data={data} groups={["storyDevelopment","characterBuilding","worldBuilding","dialogueStyle"]}/>;case"questionsAboutPlot":return <QuestionsView data={data} groups={["coreQuestions","structureFlow","conflictTension","endingResolution"]}/>;case"actStructureSetup":return <ActView data={data} groups={[["actOneOpeningScene","Act One - Opening Scene",["scenePlace","tone","introduceProtagonistOrdinaryWorld","establishSettingToneAtmosphere","setupProtagonistGoalsDesireConflicts"]],["actOneDevelopment","Act One - Development",["introduceImportantSecondaryCharacters","protagonistInitialAttemptsToAddressConflict","raiseStakesLeadingToActTwo"]]]}/>;case"actStructureConfrontation":return <ActView data={data} groups={[["actTwoMidpointComplications","Act Two - Midpoint Complications",["revelationChangesDirectionOrUnderstanding","shiftProtagonistGoalsMotivationPerspective","introduceNewObstaclesConflictsAntagonisticForce","increaseTensionRaiseStakesFurther","testProtagonistResolveSkillsBeliefs"]],["actTwoRisingAction","Act Two - Rising Action",["presentSeriesOfChallenges","introduceSubplotsAndComplexNarrative","deepenCharacterRelationshipsAndEscalateConflict"]]]}/>;case"actStructureResolution":return <ActView data={data} groups={[["actThreeFallingAction","Act Three - Falling Action",["resolveSubplotsTieLooseEnds","revealConsequence","provideClosureToCharacterArcAndRelationship"]],["actThreeClimax","Act Three - Climax",["finalConfrontationBetweenProtagonistAndAntagonist","highestPointOfTensionOutcomeAtStake","showProtagonistGrowthLossOrConsequences"]],["actThreeResolution","Act Three - Resolution",["ultimateTriumphOrResolutionOfMainConflict","reflectThemesMessagesLessons","closure"]]]}/>;case"actWritingPages":return <ActWritingPagesView data={data}/>;default:return null}}
