import "../../../styles/forms/ResearchInspirationForms.css";
const rows=value=>Array.isArray(value)?value.filter(item=>item!==null&&item!==undefined&&item!==""):[];
const show=value=>value===null||value===undefined||value===""?"—":String(value);
function Lines({items}){const values=rows(items);return values.length?<ul>{values.map((item,index)=><li key={index}>{show(item)}</li>)}</ul>:<p>—</p>}
function Facts({items}){return <dl className="research-view-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl>}
function Block({title,children}){return <section className="research-view-block"><h3>{title}</h3>{children}</section>}
function Cards({title,items,children}){return <Block title={title}><div className="research-view-cards">{rows(items).map((row,index)=><article key={row._id||index}>{children(row,index)}</article>)}</div></Block>}
function Notes({data}){return <Block title="Notes"><Lines items={data.notes}/></Block>}
function Topics({data}){return <div className="research-view"><Cards title="Research Topics" items={data.topics}>{row=><Facts items={[["Topic / Idea",row.topicIdea],["Research Question",row.researchQuestion],["Priority",row.priority],["Category",row.category]]}/>}</Cards><Notes data={data}/></div>}
function ResearchNotes({data}){return <div className="research-view"><Facts items={[["Research Topic",data.researchTopic],["Expanded Notes",data.expandedNotes]]}/><Notes data={data}/></div>}
function Log({data}){return <div className="research-view"><h2>{show(data.topicTitle)}</h2><div className="research-view-columns"><Block title="What I Need to Know"><Lines items={data.whatDoINeedToKnow}/></Block><Block title="Key Findings"><Lines items={data.keyFindings}/></Block></div><Cards title="Sources / References" items={data.sourcesReferences}>{row=><Facts items={[["Source",row.source],["Type",row.type],["Notes",row.notes]]}/>}</Cards><Block title="How It Relates to My Project"><p>{show(data.howItRelatesToMyProject)}</p></Block><Notes data={data}/></div>}
function Influences({data}){return <div className="research-view"><Cards title="Authors / People" items={data.authorsPeopleThatInfluencedYou}>{row=><Facts items={[["Title / Work",row.title],["Author / Person",row.author],["Contribution",row.whatItContributed]]}/>}</Cards><Cards title="Films / Shows / Games" items={data.filmsShowsGamesThatInspiredYou}>{row=><Facts items={[["Title",row.title],["Source",row.source],["Contribution",row.whatItContributed]]}/>}</Cards><Block title="Visual / Cultural / Life Influences"><Lines items={data.visualCulturalLifeInfluences}/></Block><Notes data={data}/></div>}
function Books({data}){return <div className="research-view"><Cards title="Inspiring Books" items={data.books}>{row=><><Facts items={[["Title",row.title],["Author",row.author],["Genre",row.genre],["Publisher",row.publisher],["Rating",row.rating],["Best Quote",row.bestQuote],["What Inspired Me",row.thingThatInspireYou]]}/><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
function Publications({data}){return <div className="research-view"><Cards title="Books / Publications" items={data.publications}>{row=><Facts items={[["Title",row.title],["Author",row.author],["Year",row.publicationYear],["Topic / Genre",row.topicGenre],["Key Takeaways",row.keyTakeawaysNotes],["Use for My Project",row.howItsUsefulForMyProject]]}/>}</Cards><Notes data={data}/></div>}
function Quotes({data,title}){return <div className="research-view"><Cards title={title} items={data.quotes}>{row=><><blockquote>{show(row.quote)}</blockquote><Facts items={[["Author / Source",row.authorSource],["Book / Article",row.bookArticle],["Topic / Genre",row.topicGenre]]}/><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
const questionGroups=[["Topic Clarity","topicClarity"],["Source Evaluation","sourceEvaluation"],["Application to Story","applicationToStory"],["Other Questions","others"]];
function Questions({data}){return <div className="research-view">{questionGroups.map(([title,key])=><Cards key={key} title={title} items={data[key]}>{row=><Facts items={[["Question",row.question],["Response",row.response]]}/>}</Cards>)}<Notes data={data}/></div>}
function Gallery({data}){return <div className="research-view"><Cards title="Inspiration Gallery" items={data.galleryItems}>{row=><><Facts items={[["Quote",row.quote],["Texture",row.texture],["Symbol",row.symbol],["Represents",row.represents]]}/><Block title="Color Palette"><Lines items={row.colorPalette}/></Block><Lines items={row.notes}/></>}</Cards><Notes data={data}/></div>}
function InspirationNotes({data}){return <div className="research-view research-view-columns"><Block title="Quotes That Moved Me"><Lines items={data.quoteThatMovedMe}/></Block><Block title="Visuals I Keep Picturing"><Lines items={data.visualIKeepPicturing}/></Block><Block title="Feelings I Want to Capture"><Lines items={data.feelingIWantToCapture}/></Block><Notes data={data}/></div>}
export default function ResearchInspirationView({pageKey,data}){switch(pageKey){case"researchTopics":return <Topics data={data}/>;case"researchNotes":return <ResearchNotes data={data}/>;case"researchLog":return <Log data={data}/>;case"inspirationsInfluences":return <Influences data={data}/>;case"inspiringBooks":return <Books data={data}/>;case"booksPublications":return <Publications data={data}/>;case"documentedQuotes":return <Quotes data={data} title="Documented Quotes"/>;case"questionsThatHelp":return <Questions data={data}/>;case"inspirationGallery":return <Gallery data={data}/>;case"inspirationNotes":return <InspirationNotes data={data}/>;case"inspirationalQuotes":return <Quotes data={data} title="Inspirational Quotes"/>;default:return null}}
