import "../../../styles/forms/RevisionEditingForms.css";
const rows=value=>Array.isArray(value)?value.filter(item=>item!==null&&item!==undefined&&item!==""):[];
const show=value=>value===null||value===undefined||value===""?"—":String(value);
function Lines({items}){const values=rows(items);return values.length?<ul>{values.map((item,index)=><li key={index}>{show(item)}</li>)}</ul>:<p>—</p>}
function Facts({items}){return <dl className="revision-view-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl>}
function NotesView({data}){return <div className="revision-view"><section className="revision-view-table"><div className="revision-view-table-head"><span>Page</span><span>Revision Note</span></div>{rows(data.revisionNotes).map((row,index)=><div className="revision-view-table-row" key={row._id||index}><span>{show(row.pageNumber)}</span><span>{show(row.revisionNote)}</span></div>)}</section><Lines items={data.notes}/></div>}
const revisionGroups=[["Plot & Structure","plotStructure"],["Character Development","characterDevelopment"],["Setting & World-Building","settingWorldBuilding"]];
const authorialGroups=[["Pre-Writing Phase","preWritingPhase"],["Writing Phase","writingPhase"],["Research & Inspiration","researchInspiration"],["Feedback & Revision","feedbackRevision"],["Publishing Preparation","publishingPreparation"],["Marketing & Launch","marketingLaunch"],["Mindset & Motivation","mindsetMotivation"]];
function ChecklistView({data,groups}){const info=data.projectInfo||{};return <div className="revision-view"><Facts items={[["Project Title",info.projectTitle],["Date Started",info.dateStarted?new Date(info.dateStarted).toLocaleDateString():"—"],["Date Completed",info.dateCompleted?new Date(info.dateCompleted).toLocaleDateString():"—"],["Theme",info.theme],["Genre",info.genre],["Expected Word Count",Number(info.expectedWordCount||0).toLocaleString()]]}/>{groups.map(([title,key])=><section className="revision-view-group" key={key}><h3>{title}</h3>{rows(data[key]).map((row,index)=><article key={row._id||index}><span className={`revision-status revision-status-${String(row.status||"unset").toLowerCase().replaceAll(" ","-")}`}>{show(row.status)}</span><h4>{show(row.question)}</h4><Lines items={row.notes}/></article>)}</section>)}<Lines items={data.notes}/></div>}
export default function RevisionEditingView({pageKey,data}){switch(pageKey){case"revisionNotes":return <NotesView data={data}/>;case"revisionChecklist":return <ChecklistView data={data} groups={revisionGroups}/>;case"authorialChecklist":return <ChecklistView data={data} groups={authorialGroups}/>;default:return null}}
