import "../../../styles/forms/WorldBuildingForms.css";

const rows=value=>Array.isArray(value)?value.filter(item=>item!==null&&item!==undefined&&item!==""):[];
const show=value=>value===null||value===undefined||value===""?"—":String(value);
const heading=key=>key.replace(/([A-Z])/g," $1").replace(/^./,letter=>letter.toUpperCase());
function Lines({items}){const list=rows(items);return list.length?<ul>{list.map((item,index)=><li key={item?._id||index}>{show(typeof item==="object"?item.text:item)}</li>)}</ul>:<p>—</p>}
function Facts({items}){return <dl className="world-view-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl>}
function Block({title,children}){return <section className="world-view-block"><h4>{title}</h4>{children}</section>}
function ListBlocks({data,keys}){return <div className="world-view-columns">{keys.map(key=><Block key={key} title={heading(key)}><Lines items={data?.[key]}/></Block>)}</div>}

function PrimarySettingsView({data}){return <div className="world-view world-view-grid">{rows(data).map((item,index)=><article className="world-view-card" key={item._id||index}><header><p>Primary Setting {index+1}</p><h3>{show(item.settingName)}</h3></header><Facts items={[["Location Type",item.locationType],["Importance to Story",item.importanceToStory],["Recurring Themes / Moods",item.recurringThemesMoods]]}/><ListBlocks data={item} keys={["descriptionVisualFeel","keyLandmarksOrFeatures","notes"]}/></article>)}</div>}
function SettingDescriptionView({data}){return <div className="world-view"><article className="world-view-card"><header><h3>{show(data.settingName)}</h3></header><Block title="Purpose in Story"><Facts items={[["Action Scene",data.purposeInStory?.actionScene],["Revelation",data.purposeInStory?.revelation],["Emotional Moment",data.purposeInStory?.emotionalMoment],["Character Growth",data.purposeInStory?.characterGrowth]]}/><Lines items={data.purposeInStory?.other}/></Block><Block title="Visual Aesthetic / Mood Words"><p>{show(data.visualAestheticMoodWords)}</p></Block><Block title="Sensory Details"><Facts items={[["Sights",data.visualAestheticMood?.sights],["Sounds",data.visualAestheticMood?.sounds],["Smells",data.visualAestheticMood?.smells],["Textures / Feel",data.visualAestheticMood?.texturesFeel],["Weather / Lighting",data.visualAestheticMood?.weatherLighting],["Detail or Symbol",data.visualAestheticMood?.detailOrSymbol],["Other",data.visualAestheticMood?.other]]}/></Block><ListBlocks data={data} keys={["description","notes"]}/></article></div>}
function TimePeriodView({data}){return <div className="world-view"><article className="world-view-card"><Facts items={[["Time Setting",data.timeSetting],["World / Time Type",data.worldTimeType]]}/><Block title="Key Features"><Facts items={[["Technology Level",data.keyFeatures?.technologyLevel],["Clothing Style",data.keyFeatures?.clothingStyle],["Social Structure",data.keyFeatures?.socialStructure],["Common Language or Slang",data.keyFeatures?.commonLanguageOrSlang],["Transportation",data.keyFeatures?.transportation],["Other",data.keyFeatures?.other]]}/></Block><ListBlocks data={data} keys={["importantEventsHappeningDuringThisTime","howTimeAffectsYourStory","notesForFutureUse"]}/></article></div>}
function AtmosphereView({data}){return <div className="world-view"><article className="world-view-card"><Block title="Overall Mood"><p>{show(data.overallMood)}</p></Block><Block title="Purpose of Mood"><Facts items={[["Build Tension",data.purposeOfMood?.buildTension],["Show Romance",data.purposeOfMood?.showRomance],["Reveal Danger",data.purposeOfMood?.revealDanger],["Create Peace",data.purposeOfMood?.createPeace]]}/><Lines items={data.purposeOfMood?.other}/></Block><ListBlocks data={data} keys={["atmosphereDetails","charactersReactions","notes"]}/></article></div>}
function CulturalContextView({data}){return <div className="world-view"><article className="world-view-card"><Facts items={[["Belief Systems / Religions",data.beliefSystemsReligions],["Social Structure",data.socialStructure],["Impact on Plot or Characters",data.howThisImpactsThePlotOrCharacters]]}/><ListBlocks data={data} keys={["clothingTraditionsCustoms","languageCommunicationStyle","lawsRulesJusticeSystem","economyOccupations","notes"]}/></article></div>}
function LandmarksView({data}){return <div className="world-view"><section className="world-view-table"><h3>Landmarks</h3><div className="world-view-table-head world-landmark-columns"><span>Name</span><span>Type</span><span>Location</span><span>Significance</span><span>Special Notes</span></div>{rows(data.landmarks).map((item,index)=><div className="world-view-table-row world-landmark-columns" key={item._id||index}><span>{show(item.name)}</span><span>{show(item.type)}</span><span>{show(item.location)}</span><span>{show(item.significance)}</span><span>{show(item.specialNotes)}</span></div>)}</section><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function LocationsMapView({data}){return <div className="world-view"><div className="world-view-map-images">{data.mapImageUrl?<figure><img src={data.mapImageUrl} alt="World map"/><figcaption>Map</figcaption></figure>:null}{data.sketchImageUrl?<figure><img src={data.sketchImageUrl} alt="World map sketch"/><figcaption>Sketch</figcaption></figure>:null}</div><section className="world-view-table"><h3>Location Pins</h3><div className="world-view-table-head world-pin-columns"><span>Label</span><span>Description</span><span>X</span><span>Y</span><span>Notes</span></div>{rows(data.locationPins).map((item,index)=><div className="world-view-table-row world-pin-columns" key={item._id||index}><span>{show(item.label)}</span><span>{show(item.description)}</span><span>{show(item.x)}</span><span>{show(item.y)}</span><span>{rows(item.notes).join("; ")||"—"}</span></div>)}</section><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function SettingInteractionView({data}){return <div className="world-view"><article className="world-view-card"><header><h3>{show(data.settingName)}</h3></header><Block title="Characters Who Visit This Setting">{rows(data.charactersWhoVisitThisSetting).map((item,index)=><div className="world-view-row" key={item._id||index}><strong>{show(item.characterName)}</strong><span>{rows(item.notes).join("; ")||"—"}</span></div>)}</Block><ListBlocks data={data} keys={["whatDoTheyDoHere","howSettingAffectsMoodOrBehavior","plotPointsThatOccurHere","additionalNotes","notes"]}/></article></div>}
function HistoricalBackgroundView({data}){return <div className="world-view"><article className="world-view-card"><Block title="Important Figures from the Past">{rows(data.importantFiguresFromThePast).map((item,index)=><div className="world-view-row" key={item._id||index}><strong>{show(item.name)}</strong><span>{show(item.role)}</span></div>)}</Block><ListBlocks data={data} keys={["keyHistoricalEvents","turningPoints","mythsLegendsStories","howThisHistoryAffectsTheCurrentStory","notes"]}/></article></div>}
function TechnologyView({data}){return <div className="world-view"><article className="world-view-card"><Facts items={[["Technology Level",data.technologyLevel],["Technology Access",data.technologyAccess],["How It Affects the Plot",data.howItAffectsThePlot]]}/><Block title="Infrastructure Systems"><Facts items={[["Transportation",data.infrastructureSystems?.transportation],["Energy / Power",data.infrastructureSystems?.energyPower],["Communication",data.infrastructureSystems?.communication],["Primary Facilities",data.infrastructureSystems?.primaryFacilities],["Other",data.infrastructureSystems?.other]]}/></Block><ListBlocks data={data} keys={["commonToolsDevicesUsed","notes"]}/></article></div>}
function CulturalDiversityView({data}){return <div className="world-view"><article className="world-view-card"><Block title="Cultures or Groups Represented">{rows(data.culturesOrGroupsRepresented).map((item,index)=><div className="world-view-row world-view-row-three" key={item._id||index}><strong>{show(item.name)}</strong><span>{show(item.locationRegion)}</span><span>{show(item.specificCharacteristics)}</span></div>)}</Block><Block title="Traditions / Celebrations">{rows(data.traditionsCelebrations).map((item,index)=><div className="world-view-row world-view-row-three" key={item._id||index}><strong>{show(item.culture)}</strong><span>{show(item.celebration)}</span><span>{show(item.whenWhy)}</span></div>)}</Block><Facts items={[["Languages / Dialects",data.languagesDialects],["Intercultural Relationships",data.interculturalRelationships]]}/><ListBlocks data={data} keys={["foodDressArtStyles","howCulturalDiversityEnrichesThePlot","notes"]}/></article></div>}

export default function WorldBuildingView({pageKey,data}){switch(pageKey){case"primarySettings":return <PrimarySettingsView data={data}/>;case"settingDescription":return <SettingDescriptionView data={data}/>;case"timePeriod":return <TimePeriodView data={data}/>;case"atmosphereMood":return <AtmosphereView data={data}/>;case"culturalSocialContext":return <CulturalContextView data={data}/>;case"landmarkOverview":return <LandmarksView data={data}/>;case"keyLocationsMap":return <LocationsMapView data={data}/>;case"settingInteraction":return <SettingInteractionView data={data}/>;case"historicalBackground":return <HistoricalBackgroundView data={data}/>;case"technologyInfrastructure":return <TechnologyView data={data}/>;case"culturalDiversity":return <CulturalDiversityView data={data}/>;default:return null}}
