import "../../../styles/forms/WritingProgressForms.css";
const rows=value=>Array.isArray(value)?value.filter(item=>item!==null&&item!==undefined&&item!==""):[];const show=value=>value===null||value===undefined||value===""?"—":String(value);const heading=key=>key.replace(/([A-Z])/g," $1").replace(/^./,letter=>letter.toUpperCase());const date=value=>value?new Date(value).toLocaleDateString():"—";
function Lines({items}){const values=rows(items);return values.length?<ul>{values.map((item,index)=><li key={index}>{show(item)}</li>)}</ul>:<p>—</p>}
function Facts({items}){return <dl className="writing-view-facts">{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{show(value)}</dd></div>)}</dl>}
function Block({title,children}){return <section className="writing-view-block"><h4>{title}</h4>{children}</section>}
function ListBlocks({data,keys}){return <div className="writing-view-columns">{keys.map(key=><Block key={key} title={heading(key)}><Lines items={data?.[key]}/></Block>)}</div>}
function Table({title,columns,items}){const columnClass=`writing-view-columns-${columns.length}`;return <section className="writing-view-table"><h3>{title}</h3><div className={`writing-view-table-head ${columnClass}`}>{columns.map(([label])=><span key={label}>{label}</span>)}</div>{rows(items).map((item,index)=><div className={`writing-view-table-row ${columnClass}`} key={item._id||index}>{columns.map(([label,key,format])=><span key={key}>{format?format(item[key]):show(item[key])}</span>)}</div>)}</section>}
function WritingStyleView({data}){return <div className="writing-view"><article className="writing-view-card"><Facts items={[["Narrative Voice",data.narrativeVoice],["First Person",data.firstPerson],["Second Person",data.secondPerson],["Third Person Omniscient",data.thirdPersonOmniscient]]}/><ListBlocks data={data} keys={["languageStyles","notes"]}/></article></div>}
function WritingGoalsView({data}){return <div className="writing-view"><Table title="Time-Based Goals" columns={[["Timeframe","timeframe"],["Goal","goalDescription"],["Deadline","deadline",date],["Status","status"]]} items={data.timeBasedGoals}/><Table title="Project-Specific Goals" columns={[["Project","projectTitle"],["Word Count Goal","wordCountGoal",value=>Number(value||0).toLocaleString()],["Pages","pagesToFinish"],["Start Date","startDate",date],["Deadline","deadline",date],["Progress Notes","progressNotes",value=>rows(value).join("; ")||"—"]]} items={data.projectSpecificGoals}/><Block title="Motivation / Rewards"><p>{show(data.motivationRewards)}</p></Block><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function GoalPlanView({data}){return <div className="writing-view writing-view-grid">{rows(data.goals).map((item,index)=><article className="writing-view-card" key={item._id||index}><header><p>Goal {index+1}</p><h3>{show(item.goal)}</h3></header><Facts items={[["Start Date",date(item.startDate)],["Deadline",date(item.deadline)],["Completed Status",item.completedStatus]]}/><ListBlocks data={item} keys={["actionSteps","notes"]}/></article>)}<Block title="General Notes"><Lines items={data.notes}/></Block></div>}
function WordCountView({data}){return <div className="writing-view"><Table title="Word Count Tracker" columns={[["Date","date",date],["Word Count","wordCount",value=>Number(value||0).toLocaleString()],["Target","target",value=>Number(value||0).toLocaleString()],["Difference","targetDifference",value=>Number(value||0).toLocaleString()],["Time Total","timeTotal"],["Total Count","totalCount",value=>Number(value||0).toLocaleString()],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={data.entries}/><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function WritingTrackerView({data}){return <div className="writing-view"><div className="writing-view-columns"><Block title="Progress Key"><Lines items={data.progressKey}/></Block><Block title="Custom Progress Key"><Lines items={data.customProgressKey}/></Block></div><Table title="Yearly Progress" columns={[["Month","month"],["Day","day"],["Progress Amount","progressAmount"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={data.yearlyProgress}/><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function Tasks({title,items}){return <Table title={title} columns={[["Task","task"],["Status","status"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={items}/>}
function DailyView({data}){return <div className="writing-view writing-view-grid">{rows(data).map((item,index)=><article className="writing-view-card" key={item._id||index}><header><p>Daily Planner {index+1}</p><h3>{date(item.date)}</h3></header><Table title="Schedule" columns={[["Time","time"],["Task","task"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={item.schedule}/><Block title="Priorities"><Lines items={item.priorities}/></Block><Tasks title="To-Do List" items={item.toDoList}/><Block title="Affirmation"><p>{show(item.affirmation)}</p></Block><Block title="Notes"><Lines items={item.notes}/></Block></article>)}</div>}
function WeeklyView({data}){return <div className="writing-view">{rows(data).map((item,index)=><article className="writing-view-card" key={item._id||index}><header><p>Weekly Planner {index+1}</p><h3>{show(item.week)}</h3></header><div className="writing-view-week">{["monday","tuesday","wednesday","thursday","friday","saturday","sunday"].map(key=><Block key={key} title={heading(key)}><p>{show(item[key])}</p></Block>)}</div><Block title="This Week's Goals"><Lines items={item.thisWeekGoals}/></Block><Tasks title="To-Do List" items={item.toDoList}/><Block title="Notes"><Lines items={item.notes}/></Block></article>)}</div>}
function MonthlyView({data}){return <div className="writing-view">{rows(data).map((item,index)=><article className="writing-view-card" key={item._id||index}><header><p>Monthly Planner {index+1}</p><h3>{show(item.month)} {show(item.year)}</h3></header><Table title="Calendar Days" columns={[["Day","dayNumber"],["Weekday","weekday"],["Content","content"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={item.days}/><Tasks title="Monthly Tasks" items={item.monthlyTasks}/><Block title="Affirmation"><p>{show(item.affirmation)}</p></Block><Block title="Notes"><Lines items={item.notes}/></Block></article>)}</div>}
function ToDoView({data}){return <div className="writing-view"><Tasks title="Daily To-Do List" items={data.dailyToDoList}/><Tasks title="Weekly To-Do List" items={data.weeklyToDoList}/><Tasks title="Monthly To-Do List" items={data.monthlyToDoList}/><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function PomodoroView({data}){return <div className="writing-view writing-view-grid">{rows(data).map((item,index)=><article className="writing-view-card" key={item._id||index}><header><p>Pomodoro Tracker {index+1}</p><h3>{date(item.date)}</h3></header><Facts items={[["Month",item.month],["Day",item.day],["Productivity Level",item.productivityLevel]]}/><Table title="Tasks for Today" columns={[["Task","task"],["Target","target"],["Actual","actual"],["Spent","spent"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={item.tasksForToday}/><Table title="Timed Tasks" columns={[["Task","task"],["Start Time","startTime"],["End Time","endTime"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={item.tasks}/><ListBlocks data={item} keys={["breaks","notes"]}/></article>)}</div>}
function ChapterProgressView({data}){return <div className="writing-view"><Table title="Chapter Progress" columns={[["Chapter","chapterNumber"],["Title / Working Title","titleWorkingTitle"],["Writing Dates","writingDates",value=>rows(value).map(date).join("; ")||"—"],["Word Count","wordCount",value=>Number(value||0).toLocaleString()],["Goal Met","goalMet"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={data.chapters}/><Block title="Notes"><Lines items={data.notes}/></Block></div>}
function ProjectOverviewView({data}){return <div className="writing-view"><Table title="Projects" columns={[["Project Title","projectTitle"],["Type","type"],["Genre","genre"],["Start Date","startDate",date],["Target Deadline","targetDeadline",date],["Status","status"]]} items={data.projects}/><Table title="Progress Milestones" columns={[["Project","projectTitle"],["Stage","stage"],["Percent Complete","percentComplete",value=>`${Number(value||0)}%`],["Last Worked On","lastWorkedOn",date],["Next Task","nextTask"]]} items={data.progressMilestones}/><ListBlocks data={data} keys={["notesIdeas","notes"]}/></div>}
function ProjectTrackersView({data}){return <div className="writing-view">{rows(data).map((item,index)=><article className="writing-view-card" key={item._id||index}><header><p>Project Tracker {index+1}</p><h3>{show(item.projectName)}</h3></header><Facts items={[["Start Date",date(item.startDate)],["End Date",date(item.endDate)]]}/><Table title="Tasks" columns={[["Task","task"],["Start Date","startDate",date],["End Date","endDate",date],["Days Worked","daysWorked",value=>rows(value).join("; ")||"—"],["Status","status"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={item.tasks}/><Block title="Notes"><Lines items={item.notes}/></Block></article>)}</div>}
function ProjectTeamsView({data}){return <div className="writing-view">{rows(data).map((item,index)=><article className="writing-view-card" key={item._id||index}><header><p>Project Team {index+1}</p><h3>{show(item.projectName)}</h3></header><Table title="Team Members" columns={[["Name","name"],["Role","role"],["Responsibilities","responsibilities"],["Phone","phone"],["Email","email"],["Notes","notes",value=>rows(value).join("; ")||"—"]]} items={item.teamMembers}/><Block title="Notes"><Lines items={item.notes}/></Block></article>)}</div>}
export default function WritingProgressView({pageKey,data}){switch(pageKey){case"writingStyle":return <WritingStyleView data={data}/>;case"writingGoals":return <WritingGoalsView data={data}/>;case"writingGoalPlan":return <GoalPlanView data={data}/>;case"wordCountTracker":return <WordCountView data={data}/>;case"writingTracker":return <WritingTrackerView data={data}/>;case"dailyPlanners":return <DailyView data={data}/>;case"weeklyPlanners":return <WeeklyView data={data}/>;case"monthlyPlanners":return <MonthlyView data={data}/>;case"toDoList":return <ToDoView data={data}/>;case"pomodoroTrackers":return <PomodoroView data={data}/>;case"chapterProgressTracker":return <ChapterProgressView data={data}/>;case"projectOverview":return <ProjectOverviewView data={data}/>;case"projectTrackers":return <ProjectTrackersView data={data}/>;case"projectTeams":return <ProjectTeamsView data={data}/>;default:return null}}
