import {useEffect,useState} from "react";
import {Alert,Button,Card,Col,Form,Row,Spinner} from "react-bootstrap";
import {useLocation,useNavigate,useParams} from "react-router-dom";
import "../../styles/operations.css";

const emptyClient={name:"",firstName:"",lastName:"",company:"",clientType:"Individual",email:"",phone:"",altPhone:"",preferredContactMethod:"Email",address1:"",address2:"",city:"",state:"",country:"",postalCode:"",billingContactName:"",billingEmail:"",billingPhone:"",taxExempt:false,taxExemptNumber:"",defaultServiceType:"",dietaryRequirements:"",allergies:"",favoriteMenus:"",deliveryInstructions:"",paymentTerms:"",referralSource:"",lastEventDate:"",status:"active",notes:""};

export default function ClientForm(){
 const {id}=useParams();const location=useLocation();const navigate=useNavigate();const readOnly=!!id&&!location.pathname.endsWith("/edit");
 const [formData,setFormData]=useState(emptyClient);const [countries,setCountries]=useState([]);const [states,setStates]=useState([]);const [loading,setLoading]=useState(!!id);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{let ignore=false;Promise.all([fetch("/api/countries").then(r=>r.json()),fetch("/api/states").then(r=>r.json()),id?fetch(`/api/clients/${id}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"Client could not be loaded.");return d.client||d.data;}):null]).then(([countryData,stateData,client])=>{if(ignore)return;setCountries(countryData.countries||countryData.data||countryData||[]);setStates(stateData.states||stateData.data||stateData||[]);if(client)setFormData({...emptyClient,...client,state:client.state?._id||client.state||"",country:client.country?._id||client.country||"",lastEventDate:client.lastEventDate?String(client.lastEventDate).slice(0,10):""});}).catch(err=>!ignore&&setError(err.message)).finally(()=>!ignore&&setLoading(false));return()=>{ignore=true;};},[id]);
 const change=e=>{const {name,value,type,checked}=e.target;setFormData(current=>({...current,[name]:type==="checkbox"?checked:value,...(name==="country"?{state:""}:{})}));};
 const save=async e=>{e.preventDefault();try{setSaving(true);setError("");const payload={...formData,name:formData.name||`${formData.firstName} ${formData.lastName}`.trim(),state:formData.state||null,country:formData.country||null};const res=await fetch(id?`/api/clients/${id}`:"/api/clients",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.message||"Client could not be saved.");navigate("/clients");}catch(err){setError(err.message);}finally{setSaving(false);}};
 const field=(name,label,type="text",required=false)=><Col md={6}><Form.Group><Form.Label>{label}</Form.Label><Form.Control name={name} type={type} value={formData[name]} onChange={change} disabled={readOnly} required={required}/></Form.Group></Col>;
 const area=(name,label)=><Col xs={12}><Form.Group><Form.Label>{label}</Form.Label><Form.Control as="textarea" rows={3} name={name} value={formData[name]} onChange={change} disabled={readOnly}/></Form.Group></Col>;
 const section=(title,children)=><Card className="operation-form-section"><Card.Header>{title}</Card.Header><Card.Body><Row className="g-3">{children}</Row></Card.Body></Card>;
 if(loading)return <div className="operation-form-page text-center py-5"><Spinner animation="border"/></div>;
 return <section className="operation-form-page"><header className="operation-form-header"><div><p>Client Operations</p><h1>{readOnly?"Client Details":id?"Edit Client":"Create Client"}</h1><span>Contacts, billing, service preferences, dietary needs, and delivery requirements.</span></div><Button variant="outline-secondary" onClick={()=>navigate("/clients")}>Back to Clients</Button></header>{error&&<Alert variant="danger">{error}</Alert>}<Form onSubmit={save}><div className="operation-form-grid">
 {section("Client Identity",<>{field("firstName","First Name","text",true)}{field("lastName","Last Name","text",true)}{field("name","Display Name")}{field("company","Company / Organization")}<Col md={6}><Form.Group><Form.Label>Client Type</Form.Label><Form.Select name="clientType" value={formData.clientType} onChange={change} disabled={readOnly}><option>Individual</option><option>Corporate</option><option>Nonprofit</option><option>Government</option><option>Venue Partner</option></Form.Select></Form.Group></Col><Col md={6}><Form.Group><Form.Label>Status</Form.Label><Form.Select name="status" value={formData.status} onChange={change} disabled={readOnly}><option value="active">Active</option><option value="inactive">Inactive</option></Form.Select></Form.Group></Col></>)}
 {section("Contact",<>{field("email","Email","email",true)}{field("phone","Phone","tel",true)}{field("altPhone","Alternate Phone","tel")}{field("preferredContactMethod","Preferred Contact Method")}</>)}
 {section("Address",<>{field("address1","Address Line 1")}{field("address2","Address Line 2")}{field("city","City")}<Col md={6}><Form.Group><Form.Label>Country</Form.Label><Form.Select name="country" value={formData.country} onChange={change} disabled={readOnly}><option value="">Select country</option>{countries.map(item=><option key={item._id} value={item._id}>{item.name}</option>)}</Form.Select></Form.Group></Col><Col md={6}><Form.Group><Form.Label>State</Form.Label><Form.Select name="state" value={formData.state} onChange={change} disabled={readOnly}><option value="">Select state</option>{states.map(item=><option key={item._id} value={item._id}>{item.name}</option>)}</Form.Select></Form.Group></Col>{field("postalCode","Postal Code")}</>)}
 {section("Billing & Tax",<>{field("billingContactName","Billing Contact")}{field("billingEmail","Billing Email","email")}{field("billingPhone","Billing Phone","tel")}{field("paymentTerms","Payment Terms")}<Col md={6}><Form.Check className="mt-4" name="taxExempt" checked={!!formData.taxExempt} onChange={change} disabled={readOnly} label="Tax exempt"/></Col>{field("taxExemptNumber","Tax-exempt Certificate Number")}</>)}
 {section("Catering Preferences",<>{field("defaultServiceType","Preferred Service Style")}{field("referralSource","Referral Source")}{field("lastEventDate","Last Event Date","date")}{area("dietaryRequirements","Standing Dietary Requirements")}{area("allergies","Allergies and Cross-contact Requirements")}{area("favoriteMenus","Preferred Menus and Dishes")}{area("deliveryInstructions","Default Delivery and Access Instructions")}{area("notes","Client Notes")}</>)}
 </div><footer className="operation-form-footer"><Button type="button" variant="outline-secondary" onClick={()=>navigate("/clients")}>Cancel</Button>{!readOnly&&<Button type="submit" disabled={saving}>{saving?"Saving…":"Save Client"}</Button>}{readOnly&&<Button type="button" onClick={()=>navigate(`/clients/${id}/edit`)}>Edit Client</Button>}</footer></Form></section>;
}
