import {useEffect,useState} from "react";
import {Alert,Button,Card,Col,Form,Row,Spinner} from "react-bootstrap";
import {useLocation,useNavigate,useParams} from "react-router-dom";
import "../../styles/operations.css";

const emptyEvent={eventNumber:"",eventName:"",eventType:"",clientName:"",clientEmail:"",clientPhone:"",eventDate:"",eventTime:"",endTime:"",serviceTime:"",guestCount:"",adultCount:"",childCount:"",vendorCount:"",status:"Pending",location:"",address1:"",city:"",state:"",postalCode:"",venueContact:"",venuePhone:"",serviceType:"",setupTime:"",breakdownTime:"",staffCount:"",kitchenAccess:"",powerRequirements:"",waterAccess:"",loadingInstructions:"",parkingInstructions:"",menuNotes:"",dietaryRequirements:"",allergies:"",rentalNotes:"",staffingNotes:"",timelineNotes:"",budget:"",quotedTotal:"",depositStatus:"Not Required",notes:""};

export default function EventForm(){
 const {id}=useParams();const location=useLocation();const navigate=useNavigate();
 const readOnly=!!id&&!location.pathname.endsWith("/edit");
 const [formData,setFormData]=useState(emptyEvent);const [loading,setLoading]=useState(!!id);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(!id)return;let ignore=false;fetch(`/api/events/${id}`).then(async res=>{const data=await res.json();if(!res.ok)throw new Error(data.message||"Event could not be loaded.");const event=data.event||data.data;event.eventDate=event.eventDate?String(event.eventDate).slice(0,10):"";event.notes=Array.isArray(event.notes)?event.notes.join("\n"):event.notes||"";if(!ignore)setFormData({...emptyEvent,...event});}).catch(err=>!ignore&&setError(err.message)).finally(()=>!ignore&&setLoading(false));return()=>{ignore=true;};},[id]);
 const change=e=>{const {name,value}=e.target;setFormData(current=>({...current,[name]:value}));};
 const save=async e=>{e.preventDefault();try{setSaving(true);setError("");const payload={...formData,...Object.fromEntries(["guestCount","adultCount","childCount","vendorCount","staffCount","budget","quotedTotal"].map(field=>[field,Number(formData[field]||0)])),notes:formData.notes.split("\n").map(note=>note.trim()).filter(Boolean)};const res=await fetch(id?`/api/events/${id}`:"/api/events",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.message||"Event could not be saved.");navigate("/events");}catch(err){setError(err.message);}finally{setSaving(false);}};
 const field=(name,label,type="text",required=false)=><Col md={6}><Form.Group><Form.Label>{label}</Form.Label><Form.Control name={name} type={type} value={formData[name]} onChange={change} disabled={readOnly} required={required}/></Form.Group></Col>;
 const area=(name,label)=><Col xs={12}><Form.Group><Form.Label>{label}</Form.Label><Form.Control as="textarea" rows={3} name={name} value={formData[name]} onChange={change} disabled={readOnly}/></Form.Group></Col>;
 const section=(title,children)=><Card className="operation-form-section"><Card.Header>{title}</Card.Header><Card.Body><Row className="g-3">{children}</Row></Card.Body></Card>;
 if(loading)return <div className="operation-form-page text-center py-5"><Spinner animation="border"/></div>;
 return <section className="operation-form-page"><header className="operation-form-header"><div><p>Event Operations</p><h1>{readOnly?"Event Details":id?"Edit Event":"Create Event"}</h1><span>Booking, venue, production, service, staffing, and financial requirements.</span></div><Button variant="outline-secondary" onClick={()=>navigate("/events")}>Back to Events</Button></header>{error&&<Alert variant="danger">{error}</Alert>}<Form onSubmit={save}><div className="operation-form-grid">
  {section("Booking & Client",<>{field("eventNumber","Event Number")}{field("eventName","Event Name","text",true)}{field("eventType","Event Type")}<Col md={6}><Form.Group><Form.Label>Status</Form.Label><Form.Select name="status" value={formData.status} onChange={change} disabled={readOnly}><option>Pending</option><option>Confirmed</option><option>Prep</option><option>Completed</option><option>Cancelled</option></Form.Select></Form.Group></Col>{field("clientName","Client Name","text",true)}{field("clientEmail","Client Email","email")}{field("clientPhone","Client Phone","tel")}</>)}
  {section("Schedule & Attendance",<>{field("eventDate","Event Date","date",true)}{field("eventTime","Guest Arrival / Start","time",true)}{field("serviceTime","Food Service Time","time")}{field("endTime","Event End Time","time")}{field("setupTime","Setup Start","time")}{field("breakdownTime","Breakdown Complete","time")}{field("guestCount","Guaranteed Guest Count","number",true)}{field("adultCount","Adults","number")}{field("childCount","Children","number")}{field("vendorCount","Vendor Meals","number")}</>)}
  {section("Venue & Access",<>{field("location","Venue Name","text",true)}{field("venueContact","Venue Contact")}{field("venuePhone","Venue Phone","tel")}{field("address1","Street Address")}{field("city","City")}{field("state","State / Province")}{field("postalCode","Postal Code")}{field("kitchenAccess","Kitchen Access")}{field("powerRequirements","Power Requirements")}{field("waterAccess","Water / Dishwashing Access")}{area("loadingInstructions","Loading and Delivery Instructions")}{area("parkingInstructions","Parking Instructions")}</>)}
  {section("Catering Production",<>{field("serviceType","Service Style")}{field("staffCount","Planned Staff","number")}{area("menuNotes","Menu and Portion Notes")}{area("dietaryRequirements","Dietary Requirements")}{area("allergies","Allergies and Cross-contact Notes")}{area("rentalNotes","Rental and Equipment Requirements")}{area("staffingNotes","Staff Assignments and Uniform")}{area("timelineNotes","Production and Service Timeline")}</>)}
  {section("Financial & Internal",<>{field("budget","Client Budget","number")}{field("quotedTotal","Quoted Total","number")}{field("depositStatus","Deposit Status")}{area("notes","Internal Notes — one item per line")}</>)}
 </div><footer className="operation-form-footer"><Button type="button" variant="outline-secondary" onClick={()=>navigate("/events")}>Cancel</Button>{!readOnly&&<Button type="submit" disabled={saving}>{saving?"Saving…":"Save Event"}</Button>}{readOnly&&<Button type="button" onClick={()=>navigate(`/events/${id}/edit`)}>Edit Event</Button>}</footer></Form></section>;
}
