import {useEffect,useState} from "react";
import {Alert,Button,Card,Col,Form,Row,Spinner} from "react-bootstrap";
import {useLocation,useNavigate,useParams} from "react-router-dom";
import "../../styles/operations.css";

const emptyItem={name:"",category:"",subcategory:"",sku:"",barcode:"",description:"",quantityOnHand:"",committedQuantity:"",reorderLevel:"",reorderQuantity:"",unit:"",purchaseUnit:"",conversionFactor:"",costPerUnit:"",lastPurchaseCost:"",supplier:"",supplierItemNumber:"",storageLocation:"",storageZone:"",shelfLifeDays:"",expirationTracking:false,lotTracking:false,isAllergen:false,allergenNotes:"",parLevel:"",minimumLevel:"",maximumLevel:"",countFrequency:"Weekly",status:"in-stock",notes:""};
export default function InventoryItemForm(){
 const {id}=useParams();const location=useLocation();const navigate=useNavigate();const readOnly=!!id&&!location.pathname.endsWith("/edit");
 const [formData,setFormData]=useState(emptyItem);const [loading,setLoading]=useState(!!id);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(!id)return;let ignore=false;fetch(`/api/inventory/${id}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"Inventory item could not be loaded.");if(!ignore)setFormData({...emptyItem,...(d.item||d.data)});}).catch(err=>!ignore&&setError(err.message)).finally(()=>!ignore&&setLoading(false));return()=>{ignore=true;};},[id]);
 const change=e=>{const {name,value,type,checked}=e.target;setFormData(current=>({...current,[name]:type==="checkbox"?checked:value}));};
 const save=async e=>{e.preventDefault();try{setSaving(true);setError("");const numeric=["quantityOnHand","committedQuantity","reorderLevel","reorderQuantity","conversionFactor","costPerUnit","lastPurchaseCost","shelfLifeDays","parLevel","minimumLevel","maximumLevel"];const payload={...formData,...Object.fromEntries(numeric.map(field=>[field,Number(formData[field]||0)]))};const r=await fetch(id?`/api/inventory/${id}`:"/api/inventory",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Inventory item could not be saved.");navigate("/inventory");}catch(err){setError(err.message);}finally{setSaving(false);}};
 const field=(name,label,type="text",required=false)=><Col md={4}><Form.Group><Form.Label>{label}</Form.Label><Form.Control name={name} type={type} value={formData[name]} onChange={change} disabled={readOnly} required={required}/></Form.Group></Col>;
 const area=(name,label)=><Col xs={12}><Form.Group><Form.Label>{label}</Form.Label><Form.Control as="textarea" rows={3} name={name} value={formData[name]} onChange={change} disabled={readOnly}/></Form.Group></Col>;
 const section=(title,children)=><Card className="operation-form-section"><Card.Header>{title}</Card.Header><Card.Body><Row className="g-3">{children}</Row></Card.Body></Card>;
 if(loading)return <div className="operation-form-page text-center py-5"><Spinner animation="border"/></div>;
 return <section className="operation-form-page"><header className="operation-form-header"><div><p>Kitchen Operations</p><h1>{readOnly?"Inventory Details":id?"Edit Inventory Item":"Create Inventory Item"}</h1><span>Purchasing, stocking, storage, count, food-safety, and replenishment requirements.</span></div><Button variant="outline-secondary" onClick={()=>navigate("/inventory")}>Back to Inventory</Button></header>{error&&<Alert variant="danger">{error}</Alert>}<Form onSubmit={save}><div className="operation-form-grid">
 {section("Item Identity",<>{field("name","Item Name","text",true)}{field("category","Category","text",true)}{field("subcategory","Subcategory")}{field("sku","SKU")}{field("barcode","Barcode")}<Col md={4}><Form.Group><Form.Label>Status</Form.Label><Form.Select name="status" value={formData.status} onChange={change} disabled={readOnly}><option value="in-stock">In Stock</option><option value="low">Low</option><option value="out-of-stock">Out of Stock</option><option value="discontinued">Discontinued</option></Form.Select></Form.Group></Col>{area("description","Item Description")}</>)}
 {section("Stock & Reorder",<>{field("quantityOnHand","Quantity On Hand","number")}{field("committedQuantity","Committed to Events","number")}{field("unit","Stocking Unit","text",true)}{field("parLevel","Par Level","number")}{field("minimumLevel","Minimum Level","number")}{field("maximumLevel","Maximum Level","number")}{field("reorderLevel","Reorder Point","number")}{field("reorderQuantity","Reorder Quantity","number")}{field("countFrequency","Count Frequency")}</>)}
 {section("Purchasing & Cost",<>{field("supplier","Preferred Supplier")}{field("supplierItemNumber","Supplier Item Number")}{field("purchaseUnit","Purchase Unit")}{field("conversionFactor","Units per Purchase Unit","number")}{field("costPerUnit","Average Unit Cost","number")}{field("lastPurchaseCost","Last Purchase Cost","number")}</>)}
 {section("Storage & Food Safety",<>{field("storageLocation","Storage Location")}{field("storageZone","Storage Zone / Temperature")}{field("shelfLifeDays","Shelf Life in Days","number")}<Col md={4}><Form.Check className="mt-4" name="expirationTracking" checked={!!formData.expirationTracking} onChange={change} disabled={readOnly} label="Track expiration dates"/></Col><Col md={4}><Form.Check className="mt-4" name="lotTracking" checked={!!formData.lotTracking} onChange={change} disabled={readOnly} label="Track lots"/></Col><Col md={4}><Form.Check className="mt-4" name="isAllergen" checked={!!formData.isAllergen} onChange={change} disabled={readOnly} label="Contains a declared allergen"/></Col>{area("allergenNotes","Allergen and Handling Notes")}{area("notes","Internal Inventory Notes")}</>)}
 </div><footer className="operation-form-footer"><Button type="button" variant="outline-secondary" onClick={()=>navigate("/inventory")}>Cancel</Button>{!readOnly&&<Button type="submit" disabled={saving}>{saving?"Saving…":"Save Inventory Item"}</Button>}{readOnly&&<Button type="button" onClick={()=>navigate(`/inventory/${id}/edit`)}>Edit Item</Button>}</footer></Form></section>;
}
