import {useEffect,useState} from "react";
import {Alert,Button,Card,Col,Form,Row,Spinner} from "react-bootstrap";
import {useLocation,useNavigate,useParams} from "react-router-dom";
import "../../styles/operations.css";

const emptyMenu={name:"",description:"",category:"",serviceStyle:"",occasionTypes:"",cuisine:"",pricePerGuest:"",minimumGuests:"",maximumGuests:"",foodCostTargetPercent:"",laborHoursPerGuest:"",setupMinutes:"",serviceMinutes:"",dietaryCoverage:"",allergenNotes:"",includedServices:"",excludedServices:"",equipmentRequirements:"",productionNotes:"",seasonalAvailability:"",status:"draft",notes:""};
export default function MenuForm(){
 const {id}=useParams();const location=useLocation();const navigate=useNavigate();const readOnly=!!id&&!location.pathname.endsWith("/edit");
 const [formData,setFormData]=useState(emptyMenu);const [loading,setLoading]=useState(!!id);const [saving,setSaving]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{if(!id)return;let ignore=false;fetch(`/api/menus/${id}`).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message||"Menu could not be loaded.");const menu=d.menu||d.data;if(menu.pricePerGuest?.$numberDecimal)menu.pricePerGuest=menu.pricePerGuest.$numberDecimal;if(!ignore)setFormData({...emptyMenu,...menu});}).catch(err=>!ignore&&setError(err.message)).finally(()=>!ignore&&setLoading(false));return()=>{ignore=true;};},[id]);
 const change=e=>{const {name,value}=e.target;setFormData(current=>({...current,[name]:value}));};
 const save=async e=>{e.preventDefault();try{setSaving(true);setError("");const payload={...formData,pricePerGuest:formData.pricePerGuest||0,...Object.fromEntries(["minimumGuests","maximumGuests","foodCostTargetPercent","laborHoursPerGuest","setupMinutes","serviceMinutes"].map(field=>[field,Number(formData[field]||0)]))};const r=await fetch(id?`/api/menus/${id}`:"/api/menus",{method:id?"PUT":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.message||"Menu could not be saved.");navigate("/admin/menus");}catch(err){setError(err.message);}finally{setSaving(false);}};
 const field=(name,label,type="text",required=false)=><Col md={4}><Form.Group><Form.Label>{label}</Form.Label><Form.Control name={name} type={type} value={formData[name]} onChange={change} disabled={readOnly} required={required}/></Form.Group></Col>;
 const area=(name,label)=><Col xs={12}><Form.Group><Form.Label>{label}</Form.Label><Form.Control as="textarea" rows={3} name={name} value={formData[name]} onChange={change} disabled={readOnly}/></Form.Group></Col>;
 const section=(title,children)=><Card className="operation-form-section"><Card.Header>{title}</Card.Header><Card.Body><Row className="g-3">{children}</Row></Card.Body></Card>;
 if(loading)return <div className="operation-form-page text-center py-5"><Spinner animation="border"/></div>;
 return <section className="operation-form-page"><header className="operation-form-header"><div><p>Menu Operations</p><h1>{readOnly?"Menu Details":id?"Edit Menu":"Create Menu"}</h1><span>Pricing, capacity, service, dietary, equipment, and production requirements.</span></div><Button variant="outline-secondary" onClick={()=>navigate("/admin/menus")}>Back to Menus</Button></header>{error&&<Alert variant="danger">{error}</Alert>}<Form onSubmit={save}><div className="operation-form-grid">
 {section("Menu Identity",<>{field("name","Menu / Package Name","text",true)}{field("category","Category","text",true)}{field("serviceStyle","Service Style")}{field("cuisine","Cuisine")}{field("occasionTypes","Best-fit Occasions")}{field("seasonalAvailability","Seasonal Availability")}<Col md={4}><Form.Group><Form.Label>Status</Form.Label><Form.Select name="status" value={formData.status} onChange={change} disabled={readOnly}><option value="draft">Draft</option><option value="active">Active</option><option value="inactive">Inactive</option></Form.Select></Form.Group></Col>{area("description","Public Description")}</>)}
 {section("Pricing & Capacity",<>{field("pricePerGuest","Price per Guest","number",true)}{field("minimumGuests","Minimum Guests","number",true)}{field("maximumGuests","Maximum Guests","number")}{field("foodCostTargetPercent","Food Cost Target %","number")}{field("laborHoursPerGuest","Labor Hours per Guest","number")}{field("setupMinutes","Setup Minutes","number")}{field("serviceMinutes","Expected Service Minutes","number")}</>)}
 {section("Service & Production",<>{area("includedServices","Services Included")}{area("excludedServices","Services Excluded / Add-ons")}{area("equipmentRequirements","Equipment, Rental, and Smallwares Requirements")}{area("productionNotes","Prep, Holding, Transport, and Plating Notes")}</>)}
 {section("Dietary & Internal",<>{area("dietaryCoverage","Dietary Options Supported")}{area("allergenNotes","Allergen and Cross-contact Notes")}{area("notes","Internal Menu Notes")}</>)}
 </div><footer className="operation-form-footer"><Button type="button" variant="outline-secondary" onClick={()=>navigate("/admin/menus")}>Cancel</Button>{!readOnly&&<Button type="submit" disabled={saving}>{saving?"Saving…":"Save Menu"}</Button>}{readOnly&&<Button type="button" onClick={()=>navigate(`/admin/menus/${id}/edit`)}>Edit Menu</Button>}</footer></Form></section>;
}
