import {useEffect,useMemo,useState} from "react";
import {Alert,Badge,Button,Card,Form,Table} from "react-bootstrap";
import {Link,useNavigate} from "react-router-dom";
import "../../styles/operations.css";
const money=value=>`$${Number(value||0).toFixed(2)}`;
export default function Contracts(){
 const navigate=useNavigate();const [contracts,setContracts]=useState([]);const [search,setSearch]=useState("");const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 const load=async()=>{try{const r=await fetch("/api/catering-contracts");const d=await r.json();if(!r.ok)throw new Error(d.message||"Contracts could not be loaded.");setContracts(d.data||[]);}catch(e){setError(e.message);}finally{setLoading(false);}};
 useEffect(()=>{const timer=setTimeout(load,0);return()=>clearTimeout(timer);},[]);
 const rows=useMemo(()=>contracts.filter(item=>!search||[item.contractNumber,item.clientName,item.company,item.eventName,item.eventType].some(v=>String(v||"").toLowerCase().includes(search.toLowerCase()))),[contracts,search]);
 const remove=async item=>{if(!confirm(`Delete contract ${item.contractNumber}?`))return;const r=await fetch(`/api/catering-contracts/${item._id}`,{method:"DELETE"});if(r.ok)setContracts(list=>list.filter(row=>row._id!==item._id));else setError((await r.json()).message||"Delete failed.");};
 return <section className="operations-page"><header className="operations-hero"><div><p>Contract Operations</p><h1>Catering Contracts</h1><span>Scope, pricing, deadlines, terms, acceptance, and signatures.</span></div><Button as={Link} to="/contracts/new">Add Contract</Button></header>{error&&<Alert variant="danger">{error}</Alert>}<Card className="operations-card"><Card.Header className="operations-toolbar"><Form.Control type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search contracts…"/><span>{rows.length} contracts</span></Card.Header><div className="table-responsive"><Table hover className="align-middle mb-0"><thead><tr><th>Contract</th><th>Client</th><th>Event</th><th>Event Date</th><th>Total</th><th>Deposit</th><th>Balance</th><th>Accepted</th><th>Actions</th></tr></thead><tbody>{loading&&<tr><td colSpan="9" className="text-center py-5">Loading…</td></tr>}{!loading&&!rows.length&&<tr><td colSpan="9" className="text-center py-5">No contracts found.</td></tr>}{rows.map(item=><tr key={item._id}><td>{item.contractNumber}</td><td>{item.clientName}</td><td>{item.eventName||"—"}</td><td>{item.eventDate?String(item.eventDate).slice(0,10):"—"}</td><td>{money(item.contractTotal)}</td><td>{money(item.depositPaid)}</td><td>{money(item.balance)}</td><td><Badge bg={item.clientAccepted?"success":"secondary"}>{item.clientAccepted?"Accepted":"Pending"}</Badge></td><td className="operations-actions"><Button size="sm" variant="outline-primary" onClick={()=>navigate(`/contracts/${item._id}`)}>View</Button><Button size="sm" onClick={()=>navigate(`/contracts/${item._id}/edit`)}>Edit</Button><Button size="sm" variant="outline-danger" onClick={()=>remove(item)}>Delete</Button></td></tr>)}</tbody></Table></div></Card></section>;
}
